import * as tableEnums from '../enums/table'
import * as geneEnums from '../enums/gene'

const DNA_BLUEPRINT = {
  values: {
    [tableEnums.DNA_KEYS.PRICE_DAILY_INCREASE_BUY]: geneEnums.VALUES.PRICE_DAILY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_DAILY_INCREASE_SELL]: geneEnums.VALUES.PRICE_DAILY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_DAILY_DECREASE_BUY]: geneEnums.VALUES.PRICE_DAILY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_DAILY_DECREASE_SELL]: geneEnums.VALUES.PRICE_DAILY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_WEEKLY_INCREASE_BUY]: geneEnums.VALUES.PRICE_WEEKLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_WEEKLY_INCREASE_SELL]: geneEnums.VALUES.PRICE_WEEKLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_WEEKLY_DECREASE_BUY]: geneEnums.VALUES.PRICE_WEEKLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_WEEKLY_DECREASE_SELL]: geneEnums.VALUES.PRICE_WEEKLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_MONTHLY_INCREASE_BUY]: geneEnums.VALUES.PRICE_MONTHLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_MONTHLY_INCREASE_SELL]: geneEnums.VALUES.PRICE_MONTHLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_MONTHLY_DECREASE_BUY]: geneEnums.VALUES.PRICE_MONTHLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_MONTHLY_DECREASE_SELL]: geneEnums.VALUES.PRICE_MONTHLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_QUARTERLY_INCREASE_BUY]: geneEnums.VALUES.PRICE_QUARTERLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_QUARTERLY_INCREASE_SELL]: geneEnums.VALUES.PRICE_QUARTERLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_QUARTERLY_DECREASE_BUY]: geneEnums.VALUES.PRICE_QUARTERLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_QUARTERLY_DECREASE_SELL]: geneEnums.VALUES.PRICE_QUARTERLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_YEARLY_INCREASE_BUY]: geneEnums.VALUES.PRICE_YEARLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_YEARLY_INCREASE_SELL]: geneEnums.VALUES.PRICE_YEARLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_YEARLY_DECREASE_BUY]: geneEnums.VALUES.PRICE_YEARLY_VALUES,
    [tableEnums.DNA_KEYS.PRICE_YEARLY_DECREASE_SELL]: geneEnums.VALUES.PRICE_YEARLY_VALUES,
    [tableEnums.DNA_KEYS.CASH_MAX_PERCENT]: geneEnums.VALUES.CASH_MAX_PERCENT,
    [tableEnums.DNA_KEYS.TICKET_MIN_PERCENT]: geneEnums.VALUES.TICKET_PERCENT,
    [tableEnums.DNA_KEYS.TICKET_MAX_PERCENT]: geneEnums.VALUES.TICKET_PERCENT,
    [tableEnums.DNA_KEYS.HOLDING_BUY_PERCENT]: geneEnums.VALUES.HOLDING_PERCENT,
    [tableEnums.DNA_KEYS.HOLDING_SELL_PERCENT]: geneEnums.VALUES.HOLDING_PERCENT,
    [tableEnums.DNA_KEYS.TRADE_FREQUENCY]: geneEnums.VALUES.TRADE_FREQUENCY,
    [tableEnums.DNA_KEYS.REBALANCE_FREQUENCY]: geneEnums.VALUES.REBALANCE_FREQUENCY
  },
  groups: [
    [
      tableEnums.DNA_KEYS.PRICE_DAILY_INCREASE_BUY,
      tableEnums.DNA_KEYS.PRICE_DAILY_DECREASE_BUY,
      tableEnums.DNA_KEYS.PRICE_WEEKLY_INCREASE_BUY,
      tableEnums.DNA_KEYS.PRICE_WEEKLY_DECREASE_BUY,
      tableEnums.DNA_KEYS.PRICE_MONTHLY_INCREASE_BUY,
      tableEnums.DNA_KEYS.PRICE_MONTHLY_DECREASE_BUY,
      tableEnums.DNA_KEYS.PRICE_QUARTERLY_INCREASE_BUY,
      tableEnums.DNA_KEYS.PRICE_QUARTERLY_DECREASE_BUY,
      tableEnums.DNA_KEYS.PRICE_YEARLY_INCREASE_BUY,
      tableEnums.DNA_KEYS.PRICE_YEARLY_DECREASE_BUY
    ],
    [
      tableEnums.DNA_KEYS.PRICE_DAILY_INCREASE_SELL,
      tableEnums.DNA_KEYS.PRICE_DAILY_DECREASE_SELL,
      tableEnums.DNA_KEYS.PRICE_WEEKLY_INCREASE_SELL,
      tableEnums.DNA_KEYS.PRICE_WEEKLY_DECREASE_SELL,
      tableEnums.DNA_KEYS.PRICE_MONTHLY_INCREASE_SELL,
      tableEnums.DNA_KEYS.PRICE_MONTHLY_DECREASE_SELL,
      tableEnums.DNA_KEYS.PRICE_QUARTERLY_INCREASE_SELL,
      tableEnums.DNA_KEYS.PRICE_QUARTERLY_DECREASE_SELL,
      tableEnums.DNA_KEYS.PRICE_YEARLY_INCREASE_SELL,
      tableEnums.DNA_KEYS.PRICE_YEARLY_DECREASE_SELL
    ],
    tableEnums.DNA_KEYS.CASH_MAX_PERCENT,
    tableEnums.DNA_KEYS.TICKET_MIN_PERCENT,
    tableEnums.DNA_KEYS.TICKET_MAX_PERCENT,
    tableEnums.DNA_KEYS.HOLDING_BUY_PERCENT,
    tableEnums.DNA_KEYS.HOLDING_SELL_PERCENT,
    tableEnums.DNA_KEYS.TRADE_FREQUENCY,
    tableEnums.DNA_KEYS.REBALANCE_FREQUENCY
  ]
}

export const getGeneCombinations = () => {
  return DNA_BLUEPRINT
}
