exports.up = (knex) => {
  return knex('trader').insert([
    { traderPatternId: 1, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 2, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 3, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 4, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 5, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 6, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 7, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 8, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 9, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 10, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 11, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 12, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 13, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 14, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 15, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 16, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 17, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 18, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 19, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 20, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 21, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 22, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 23, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 24, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 25, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 26, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 27, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 28, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 29, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 30, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 31, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 32, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 33, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 34, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 35, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 36, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 37, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 38, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 39, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 40, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 41, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 42, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 43, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 44, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 45, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 46, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 47, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 48, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 49, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 50, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 51, traderEnvId: 2, isActive: true, accessCode: '000' },
    { traderPatternId: 52, traderEnvId: 2, isActive: true, accessCode: '000' },
  ])
}

exports.down = () => {}
