exports.seed = (knex) => knex('trader_dna').then(() => {
  return knex('trader_dna').insert([
    {
      hashCode: 'DNA001',
      buyPreference: 1,
      sellPreference: 2,
      priceDailyIncreaseBuy: 3,
      priceDailyDecreaseSell: 3,
      cashMaxPercent: 20,
      tickerMinPercent: 2,
      tickerMaxPercent: 13,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 5,
      rebalanceFrequency: 80,
    },
    {
      hashCode: 'DNA002',
      buyPreference: 1,
      sellPreference: 2,
      priceDailyIncreaseSell: 3,
      priceDailyDecreaseBuy: 3,
      cashMaxPercent: 20,
      tickerMinPercent: 2,
      tickerMaxPercent: 13,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 5,
      rebalanceFrequency: 80,
    },
    {
      hashCode: 'DNA003',
      buyPreference: 1,
      sellPreference: 2,
      priceWeeklyIncreaseBuy: 2,
      priceWeeklyDecreaseSell: 2,
      cashMaxPercent: 20,
      tickerMinPercent: 2,
      tickerMaxPercent: 13,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 5,
      rebalanceFrequency: 80,
    },
    {
      hashCode: 'DNA004',
      buyPreference: 1,
      sellPreference: 2,
      priceWeeklyIncreaseSell: 2,
      priceWeeklyDecreaseBuy: 2,
      cashMaxPercent: 20,
      tickerMinPercent: 2,
      tickerMaxPercent: 13,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 5,
      rebalanceFrequency: 80,
    },
    {
      hashCode: 'DNA005',
      buyPreference: 1,
      sellPreference: 2,
      priceMonthlyIncreaseBuy: 2,
      priceMonthlyDecreaseSell: 2,
      cashMaxPercent: 10,
      tickerMinPercent: 1,
      tickerMaxPercent: 8,
      holdingBuyPercent: 3,
      holdingSellPercent: 20,
      tradeFrequency: 10,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA006',
      buyPreference: 1,
      sellPreference: 2,
      priceMonthlyIncreaseSell: 2,
      priceMonthlyDecreaseBuy: 2,
      cashMaxPercent: 10,
      tickerMinPercent: 1,
      tickerMaxPercent: 8,
      holdingBuyPercent: 3,
      holdingSellPercent: 20,
      tradeFrequency: 10,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA007',
      buyPreference: 1,
      sellPreference: 2,
      priceQuarterlyIncreaseBuy: 1,
      priceQuarterlyDecreaseSell: 1,
      cashMaxPercent: 10,
      tickerMinPercent: 1,
      tickerMaxPercent: 8,
      holdingBuyPercent: 3,
      holdingSellPercent: 20,
      tradeFrequency: 10,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA008',
      buyPreference: 1,
      sellPreference: 2,
      priceQuarterlyIncreaseSell: 1,
      priceQuarterlyDecreaseBuy: 1,
      cashMaxPercent: 10,
      tickerMinPercent: 1,
      tickerMaxPercent: 8,
      holdingBuyPercent: 3,
      holdingSellPercent: 20,
      tradeFrequency: 10,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA009',
      buyPreference: 1,
      sellPreference: 2,
      priceYearlyIncreaseBuy: 1,
      priceYearlyDecreaseSell: 1,
      cashMaxPercent: 20,
      tickerMinPercent: 3,
      tickerMaxPercent: 21,
      holdingBuyPercent: 5,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 0,
    },
    {
      hashCode: 'DNA010',
      buyPreference: 1,
      sellPreference: 2,
      priceYearlyIncreaseSell: 1,
      priceYearlyDecreaseBuy: 1,
      cashMaxPercent: 20,
      tickerMinPercent: 3,
      tickerMaxPercent: 21,
      holdingBuyPercent: 5,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 0,
    },
    {
      hashCode: 'DNA011',
      buyPreference: 1,
      sellPreference: 2,
      epsQuarterlyBeatsBuy: 3,
      epsQuarterlyMissSell: 3,
      cashMaxPercent: 30,
      tickerMinPercent: 2,
      tickerMaxPercent: 8,
      holdingBuyPercent: 5,
      holdingSellPercent: 10,
      tradeFrequency: 10,
      rebalanceFrequency: 40,
    },
    {
      hashCode: 'DNA012',
      buyPreference: 1,
      sellPreference: 2,
      epsQuarterlyMissBuy: 3,
      epsQuarterlyBeatsSell: 3,
      cashMaxPercent: 30,
      tickerMinPercent: 2,
      tickerMaxPercent: 8,
      holdingBuyPercent: 5,
      holdingSellPercent: 10,
      tradeFrequency: 10,
      rebalanceFrequency: 40,
    },
    {
      hashCode: 'DNA013',
      buyPreference: 1,
      sellPreference: 2,
      profitQuarterlyIncreaseBuy: 3,
      profitQuarterlyDecreaseSell: 3,
      cashMaxPercent: 30,
      tickerMinPercent: 2,
      tickerMaxPercent: 8,
      holdingBuyPercent: 5,
      holdingSellPercent: 10,
      tradeFrequency: 10,
      rebalanceFrequency: 40,
    },
    {
      hashCode: 'DNA014',
      buyPreference: 1,
      sellPreference: 2,
      profitQuarterlyDecreaseBuy: 3,
      profitQuarterlyIncreaseSell: 3,
      cashMaxPercent: 30,
      tickerMinPercent: 2,
      tickerMaxPercent: 8,
      holdingBuyPercent: 5,
      holdingSellPercent: 10,
      tradeFrequency: 10,
      rebalanceFrequency: 40,
    },
    {
      hashCode: 'DNA015',
      buyPreference: 1,
      sellPreference: 2,
      incomeQuarterlyIncreaseBuy: 3,
      incomeQuarterlyDecreaseSell: 3,
      cashMaxPercent: 50,
      tickerMinPercent: 1,
      tickerMaxPercent: 8,
      holdingBuyPercent: 3,
      holdingSellPercent: 10,
      tradeFrequency: 5,
      rebalanceFrequency: 20,
    },
    {
      hashCode: 'DNA016',
      buyPreference: 1,
      sellPreference: 2,
      incomeQuarterlyDecreaseBuy: 3,
      incomeQuarterlyIncreaseSell: 3,
      cashMaxPercent: 50,
      tickerMinPercent: 1,
      tickerMaxPercent: 8,
      holdingBuyPercent: 3,
      holdingSellPercent: 10,
      tradeFrequency: 5,
      rebalanceFrequency: 20,
    },
    {
      hashCode: 'DNA017',
      buyPreference: 1,
      sellPreference: 2,
      revenueQuarterlyIncreaseBuy: 2,
      revenueQuarterlyDecreaseSell: 2,
      cashMaxPercent: 50,
      tickerMinPercent: 1,
      tickerMaxPercent: 8,
      holdingBuyPercent: 3,
      holdingSellPercent: 10,
      tradeFrequency: 5,
      rebalanceFrequency: 20,
    },
    {
      hashCode: 'DNA018',
      buyPreference: 1,
      sellPreference: 2,
      revenueQuarterlyDecreaseBuy: 2,
      revenueQuarterlyIncreaseSell: 2,
      cashMaxPercent: 50,
      tickerMinPercent: 1,
      tickerMaxPercent: 8,
      holdingBuyPercent: 3,
      holdingSellPercent: 10,
      tradeFrequency: 5,
      rebalanceFrequency: 20,
    },
    {
      hashCode: 'DNA019',
      buyPreference: 1,
      sellPreference: 2,
      profitYearlyIncreaseBuy: 2,
      profitYearlyDecreaseSell: 2,
      cashMaxPercent: 30,
      tickerMinPercent: 2,
      tickerMaxPercent: 13,
      holdingBuyPercent: 3,
      holdingSellPercent: 30,
      tradeFrequency: 80,
      rebalanceFrequency: 320,
    },
    {
      hashCode: 'DNA020',
      buyPreference: 1,
      sellPreference: 2,
      profitYearlyDecreaseBuy: 2,
      profitYearlyIncreaseSell: 2,
      cashMaxPercent: 30,
      tickerMinPercent: 2,
      tickerMaxPercent: 13,
      holdingBuyPercent: 3,
      holdingSellPercent: 30,
      tradeFrequency: 80,
      rebalanceFrequency: 320,
    },
    {
      hashCode: 'DNA021',
      buyPreference: 1,
      sellPreference: 2,
      incomeYearlyIncreaseBuy: 1,
      incomeYearlyDecreaseSell: 1,
      cashMaxPercent: 30,
      tickerMinPercent: 2,
      tickerMaxPercent: 13,
      holdingBuyPercent: 3,
      holdingSellPercent: 30,
      tradeFrequency: 80,
      rebalanceFrequency: 320,
    },
    {
      hashCode: 'DNA022',
      buyPreference: 1,
      sellPreference: 2,
      incomeYearlyDecreaseBuy: 1,
      incomeYearlyIncreaseSell: 1,
      cashMaxPercent: 30,
      tickerMinPercent: 2,
      tickerMaxPercent: 13,
      holdingBuyPercent: 3,
      holdingSellPercent: 30,
      tradeFrequency: 80,
      rebalanceFrequency: 320,
    },
    {
      hashCode: 'DNA023',
      buyPreference: 1,
      sellPreference: 2,
      revenueYearlyIncreaseBuy: 1,
      revenueYearlyDecreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA024',
      buyPreference: 1,
      sellPreference: 2,
      revenueYearlyDecreaseBuy: 1,
      revenueYearlyIncreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA025',
      buyPreference: 1,
      sellPreference: 2,
      inflationYearlyIncreaseBuy: 1,
      inflationYearlyDecreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA026',
      buyPreference: 1,
      sellPreference: 2,
      inflationYearlyDecreaseBuy: 1,
      inflationYearlyIncreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA027',
      buyPreference: 1,
      sellPreference: 2,
      fundsRateMonthlyIncreaseBuy: 1,
      fundsRateMonthlyDecreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA028',
      buyPreference: 1,
      sellPreference: 2,
      fundsRateMonthlyDecreaseBuy: 1,
      fundsRateMonthlyIncreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA029',
      buyPreference: 1,
      sellPreference: 2,
      thirtyYearsTreasuryMonthlyIncreaseBuy: 1,
      thirtyYearsTreasuryMonthlyDecreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA030',
      buyPreference: 1,
      sellPreference: 2,
      thirtyYearsTreasuryMonthlyDecreaseBuy: 2,
      thirtyYearsTreasuryMonthlyIncreaseSell: 2,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA031',
      buyPreference: 1,
      sellPreference: 2,
      tenYearsTreasuryMonthlyIncreaseBuy: 2,
      tenYearsTreasuryMonthlyDecreaseSell: 2,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA032',
      buyPreference: 1,
      sellPreference: 2,
      tenYearsTreasuryMonthlyDecreaseBuy: 2,
      tenYearsTreasuryMonthlyIncreaseSell: 2,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA033',
      buyPreference: 1,
      sellPreference: 2,
      inflationMonthlyIncreaseBuy: 2,
      inflationMonthlyDecreaseSell: 2,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA034',
      buyPreference: 1,
      sellPreference: 2,
      inflationMonthlyDecreaseBuy: 1,
      inflationMonthlyIncreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA035',
      buyPreference: 1,
      sellPreference: 2,
      cpiMonthlyIncreaseBuy: 1,
      cpiMonthlyDecreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA036',
      buyPreference: 1,
      sellPreference: 2,
      cpiMonthlyDecreaseBuy: 1,
      cpiMonthlyIncreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA037',
      buyPreference: 1,
      sellPreference: 2,
      consumerSentimentMonthlyIncreaseBuy: 2,
      consumerSentimentMonthlyDecreaseSell: 2,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA038',
      buyPreference: 1,
      sellPreference: 2,
      consumerSentimentMonthlyDecreaseBuy: 2,
      consumerSentimentMonthlyIncreaseSell: 2,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA039',
      buyPreference: 1,
      sellPreference: 2,
      retailSalesMonthlyIncreaseBuy: 2,
      retailSalesMonthlyDecreaseSell: 2,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA040',
      buyPreference: 1,
      sellPreference: 2,
      retailSalesMonthlyDecreaseBuy: 2,
      retailSalesMonthlyIncreaseSell: 2,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA041',
      buyPreference: 1,
      sellPreference: 2,
      durableGoodsMonthlyIncreaseBuy: 1,
      durableGoodsMonthlyDecreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA042',
      buyPreference: 1,
      sellPreference: 2,
      durableGoodsMonthlyDecreaseBuy: 1,
      durableGoodsMonthlyIncreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA043',
      buyPreference: 1,
      sellPreference: 2,
      unemployeementRateMonthlyIncreaseBuy: 1,
      unemployeementRateMonthlyDecreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA044',
      buyPreference: 1,
      sellPreference: 2,
      unemployeementRateMonthlyDecreaseBuy: 1,
      unemployeementRateMonthlyIncreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA045',
      buyPreference: 1,
      sellPreference: 2,
      nonfarmPayrollMonthlyIncreaseBuy: 1,
      nonfarmPayrollMonthlyDecreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA046',
      buyPreference: 1,
      sellPreference: 2,
      nonfarmPayrollMonthlyDecreaseBuy: 1,
      nonfarmPayrollMonthlyIncreaseSell: 1,
      cashMaxPercent: 80,
      tickerMinPercent: 5,
      tickerMaxPercent: 34,
      holdingBuyPercent: 8,
      holdingSellPercent: 20,
      tradeFrequency: 40,
      rebalanceFrequency: 160,
    },
    {
      hashCode: 'DNA047',
      buyPreference: 1,
      sellPreference: 2,
      gdpYearlyChangeAboveBuy: 1,
      gdpYearlyChangeBelowSell: 1,
      cashMaxPercent: 50,
      tickerMinPercent: 5,
      tickerMaxPercent: 21,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 80,
      rebalanceFrequency: 80,
    },
    {
      hashCode: 'DNA048',
      buyPreference: 1,
      sellPreference: 2,
      gdpYearlyChangeAboveSell: 1,
      gdpYearlyChangeBelowBuy: 1,
      cashMaxPercent: 50,
      tickerMinPercent: 5,
      tickerMaxPercent: 21,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 80,
      rebalanceFrequency: 80,
    },
    {
      hashCode: 'DNA049',
      buyPreference: 1,
      sellPreference: 2,
      gdpQuarterlyChangeAboveBuy: 1,
      gdpQuarterlyChangeBelowSell: 1,
      cashMaxPercent: 50,
      tickerMinPercent: 5,
      tickerMaxPercent: 21,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 80,
      rebalanceFrequency: 80,
    },
    {
      hashCode: 'DNA050',
      buyPreference: 1,
      sellPreference: 2,
      gdpQuarterlyChangeAboveSell: 1,
      gdpQuarterlyChangeBelowBuy: 1,
      cashMaxPercent: 50,
      tickerMinPercent: 5,
      tickerMaxPercent: 21,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 80,
      rebalanceFrequency: 80,
    },
    {
      hashCode: 'DNA051',
      buyPreference: 1,
      sellPreference: 2,
      gdpQuarterlyYoYChangeAboveBuy: 2,
      gdpQuarterlyYoYChangeBelowSell: 2,
      cashMaxPercent: 50,
      tickerMinPercent: 5,
      tickerMaxPercent: 21,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 80,
      rebalanceFrequency: 80,
    },
    {
      hashCode: 'DNA052',
      buyPreference: 1,
      sellPreference: 2,
      gdpQuarterlyYoYChangeAboveSell: 2,
      gdpQuarterlyYoYChangeBelowBuy: 2,
      cashMaxPercent: 50,
      tickerMinPercent: 5,
      tickerMaxPercent: 21,
      holdingBuyPercent: 5,
      holdingSellPercent: 40,
      tradeFrequency: 80,
      rebalanceFrequency: 80,
    },
  ])
})
