exports.seed = (knex) => knex('trader').then(() => {
  return knex('trader').insert([
    { id: 1, traderDNAId: 1, traderEnvId: 1, isActive: true },
    { id: 2, traderDNAId: 2, traderEnvId: 1, isActive: true },
    { id: 3, traderDNAId: 3, traderEnvId: 1, isActive: true },
    { id: 4, traderDNAId: 4, traderEnvId: 1, isActive: true },
    { id: 5, traderDNAId: 5, traderEnvId: 1, isActive: true },
    { id: 6, traderDNAId: 6, traderEnvId: 1, isActive: true },
    { id: 7, traderDNAId: 7, traderEnvId: 1, isActive: true },
    { id: 8, traderDNAId: 8, traderEnvId: 1, isActive: true },
    { id: 9, traderDNAId: 9, traderEnvId: 1, isActive: true },
    { id: 10, traderDNAId: 10, traderEnvId: 1, isActive: true },
    { id: 11, traderDNAId: 11, traderEnvId: 1, isActive: true },
    { id: 12, traderDNAId: 12, traderEnvId: 1, isActive: true },
    { id: 13, traderDNAId: 13, traderEnvId: 1, isActive: true },
    { id: 14, traderDNAId: 14, traderEnvId: 1, isActive: true },
    { id: 15, traderDNAId: 15, traderEnvId: 1, isActive: true },
    { id: 16, traderDNAId: 16, traderEnvId: 1, isActive: true },
    { id: 17, traderDNAId: 17, traderEnvId: 1, isActive: true },
    { id: 18, traderDNAId: 18, traderEnvId: 1, isActive: true },
    { id: 19, traderDNAId: 19, traderEnvId: 1, isActive: true },
    { id: 20, traderDNAId: 20, traderEnvId: 1, isActive: true },
    { id: 21, traderDNAId: 21, traderEnvId: 1, isActive: true },
    { id: 22, traderDNAId: 22, traderEnvId: 1, isActive: true },
    { id: 23, traderDNAId: 23, traderEnvId: 1, isActive: true },
    { id: 24, traderDNAId: 24, traderEnvId: 1, isActive: true },
  ])
})
