exports.seed = (knex) => knex('trader').then(() => {
  return knex('trader').insert([
    { traderDNAId: 1, traderEnvId: 1, isActive: true },
    { traderDNAId: 2, traderEnvId: 1, isActive: true },
    { traderDNAId: 3, traderEnvId: 1, isActive: true },
    { traderDNAId: 4, traderEnvId: 1, isActive: true },
    { traderDNAId: 5, traderEnvId: 1, isActive: true },
    { traderDNAId: 6, traderEnvId: 1, isActive: true },
    { traderDNAId: 7, traderEnvId: 1, isActive: true },
    { traderDNAId: 8, traderEnvId: 1, isActive: true },
    { traderDNAId: 9, traderEnvId: 1, isActive: true },
    { traderDNAId: 10, traderEnvId: 1, isActive: true },
    { traderDNAId: 11, traderEnvId: 1, isActive: true },
    { traderDNAId: 12, traderEnvId: 1, isActive: true },
    { traderDNAId: 13, traderEnvId: 1, isActive: true },
    { traderDNAId: 14, traderEnvId: 1, isActive: true },
    { traderDNAId: 15, traderEnvId: 1, isActive: true },
    { traderDNAId: 16, traderEnvId: 1, isActive: true },
    { traderDNAId: 17, traderEnvId: 1, isActive: true },
    { traderDNAId: 18, traderEnvId: 1, isActive: true },
    { traderDNAId: 19, traderEnvId: 1, isActive: true },
    { traderDNAId: 20, traderEnvId: 1, isActive: true },
    { traderDNAId: 21, traderEnvId: 1, isActive: true },
    { traderDNAId: 22, traderEnvId: 1, isActive: true },
    { traderDNAId: 23, traderEnvId: 1, isActive: true },
    { traderDNAId: 24, traderEnvId: 1, isActive: true },
  ])
})
