export const TYPES = {
  PRICES: 'TIME_SERIES_DAILY_ADJUSTED',
  EARNINGS: 'EARNINGS',
  INCOMES: 'INCOME_STATEMENT',
  GDP: 'REAL_GDP',
  FUNDS_RATE: 'FEDERAL_FUNDS_RATE',
  TREASURY_YIELD: 'TREASURY_YIELD',
  CPI: 'CPI',
  INFLATION: 'INFLATION',
  INFLATION_EXPECTATION: 'INFLATION_EXPECTATION',
  CONSUMER_SENTIMENT: 'CONSUMER_SENTIMENT',
  RETAIL_SALES: 'RETAIL_SALES'
}

export const GDP_INTERVAL = {
  YEARLY: 'annual',
  QUARTERLY: 'quarterly'
}

export const TREASURY_TYPE = {
  '10_YEARS': '10year',
  '30_YEARS': '30year'
}
