export const NAME = {
  USER: 'user',
  TICKER: 'ticker',
  TICKER_DAILY: 'ticker_daily',
  TICKER_YEARLY: 'ticker_yearly',
  TICKER_QUARTERLY: 'ticker_quarterly',
  INDICATOR_YEARLY: 'indicator_yearly',
  INDICATOR_QUARTERLY: 'indicator_quarterly',
  INDICATOR_MONTHLY: 'indicator_monthly',
  TRADER: 'trader',
  TRADER_ENV: 'trader_env',
  TRADER_HOLDING: 'trader_holding',
  TRADER_PATTERN: 'trader_pattern',
  TRADER_FOLLOWER: 'trader_follower',
}
