export const Name = Object.freeze({
  generateSystemCaches: 'generateSystemCaches',
  sendPendingEmails: 'sendPendingEmails',
  syncTickerPrices: 'syncTickerPrices',
  syncTickerIncomes: 'syncTickerIncomes',
  syncTickerEarnings: 'syncTickerEarnings',
  syncEconomyIndicators: 'syncEconomyIndicators',
  calcPriceMovements: 'calcPriceMovements',
  calcFinancialMovements: 'calcFinancialMovements',
  calcIndicatorMovements: 'calcIndicatorMovements',
  calcDailyTickers: 'calcDailyTickers',
  calcTraderPerformances: 'calcTraderPerformances',
  calcTraderDescendants: 'calcTraderDescendants',
  calcTraderAccessHashs: 'calcTraderAccessHashs',
  generateDailyData: 'generateDailyData',
  generateWeeklyData: 'generateWeeklyData',
})
