export const Name = Object.freeze({
  syncTickerPrices: 'syncTickerPrices',
  syncTickerIncomes: 'syncTickerIncomes',
  syncTickerEarnings: 'syncTickerEarnings',
  syncMonthlyIndicators: 'syncMonthlyIndicators',
  syncQuarterlyIndicators: 'syncQuarterlyIndicators',
  syncYearlyIndicators: 'syncYearlyIndicators',
  calcPriceMovements: 'calcPriceMovements',
  calcFinancialMovements: 'calcFinancialMovements',
  calcIndicatorMovements: 'calcIndicatorMovements',
  calcDailyTickers: 'calcDailyTickers',
  calcTraderPerformances: 'calcTraderPerformances',
  calcTraderDescendants: 'calcTraderDescendants',
  calcTraderAccessHashs: 'calcTraderAccessHashs',
  sendPendingEmails: 'sendPendingEmails',
})
