exports.seed = (knex) => {
  return knex('ticker_daily').insert([
    {
      tickerId: 1,
      date: '2021-12-31',
      volume: '100000',
      closePrice: 100,
      splitMultiplier: '1.00000',
      dividendAmount: '0.00000',
      weeklyAverageFinalPrice: null,
      monthlyAverageFinalPrice: null,
      quarterlyAverageFinalPrice: null,
      yearlyAverageFinalPrice: null,
      priceDailyIncrease: null,
      priceDailyDecrease: null,
      priceWeeklyIncrease: null,
      priceWeeklyDecrease: null,
      priceMonthlyIncrease: null,
      priceMonthlyDecrease: null,
      priceQuarterlyIncrease: null,
      priceQuarterlyDecrease: null,
      priceYearlyIncrease: null,
      priceYearlyDecrease: null,
    },
    {
      tickerId: 1,
      date: '2022-01-01',
      volume: '111111',
      closePrice: 105,
      splitMultiplier: '1.00000',
      dividendAmount: '0.20000',
      weeklyAverageFinalPrice: 112,
      monthlyAverageFinalPrice: 113,
      quarterlyAverageFinalPrice: 114,
      yearlyAverageFinalPrice: 115,
      priceDailyIncrease: 1,
      priceDailyDecrease: 0,
      priceWeeklyIncrease: null,
      priceWeeklyDecrease: null,
      priceMonthlyIncrease: null,
      priceMonthlyDecrease: null,
      priceQuarterlyIncrease: null,
      priceQuarterlyDecrease: null,
      priceYearlyIncrease: null,
      priceYearlyDecrease: null,
    },
    {
      tickerId: 1,
      date: '2022-01-02',
      volume: '100111',
      closePrice: 107,
      splitMultiplier: '1.00000',
      dividendAmount: '0.00000',
      weeklyAverageFinalPrice: 111,
      monthlyAverageFinalPrice: 112,
      quarterlyAverageFinalPrice: 113,
      yearlyAverageFinalPrice: 114,
      priceDailyIncrease: 0,
      priceDailyDecrease: 1,
      priceWeeklyIncrease: 0,
      priceWeeklyDecrease: 1,
      priceMonthlyIncrease: 0,
      priceMonthlyDecrease: 1,
      priceQuarterlyIncrease: null,
      priceQuarterlyDecrease: null,
      priceYearlyIncrease: null,
      priceYearlyDecrease: null,
    },
    {
      tickerId: 1,
      date: '2022-01-03',
      volume: '999999',
      closePrice: 50,
      splitMultiplier: '2.00000',
      dividendAmount: '0.00000',
      weeklyAverageFinalPrice: 100,
      monthlyAverageFinalPrice: 104,
      quarterlyAverageFinalPrice: 105,
      yearlyAverageFinalPrice: 106,
      priceDailyIncrease: 0,
      priceDailyDecrease: 2,
      priceWeeklyIncrease: 0,
      priceWeeklyDecrease: 1,
      priceMonthlyIncrease: 0,
      priceMonthlyDecrease: 1,
      priceQuarterlyIncrease: 0,
      priceQuarterlyDecrease: 0,
      priceYearlyIncrease: null,
      priceYearlyDecrease: null,
    },
    {
      tickerId: 1,
      date: '2022-01-04',
      volume: '1022222',
      closePrice: 23,
      splitMultiplier: '4.00000',
      dividendAmount: '0.00000',
      weeklyAverageFinalPrice: 101,
      monthlyAverageFinalPrice: 105,
      quarterlyAverageFinalPrice: 106,
      yearlyAverageFinalPrice: 107,
      priceDailyIncrease: 1,
      priceDailyDecrease: 0,
      priceWeeklyIncrease: 0,
      priceWeeklyDecrease: 0,
      priceMonthlyIncrease: 1,
      priceMonthlyDecrease: 0,
      priceQuarterlyIncrease: 1,
      priceQuarterlyDecrease: 0,
      priceYearlyIncrease: 1,
      priceYearlyDecrease: 0,
    },
    {
      tickerId: 2,
      date: '2021-12-31',
      volume: '100000',
      closePrice: 32,
      splitMultiplier: '1.00000',
      dividendAmount: '0.00000',
      weeklyAverageFinalPrice: 30,
      monthlyAverageFinalPrice: 31,
      quarterlyAverageFinalPrice: 28,
      yearlyAverageFinalPrice: 35,
      priceDailyIncrease: 1,
      priceDailyDecrease: 0,
      priceWeeklyIncrease: 2,
      priceWeeklyDecrease: 0,
      priceMonthlyIncrease: 3,
      priceMonthlyDecrease: 0,
      priceQuarterlyIncrease: 2,
      priceQuarterlyDecrease: 0,
      priceYearlyIncrease: 1,
      priceYearlyDecrease: 0,
    },
    {
      tickerId: 2,
      date: '2022-01-02',
      volume: '120000',
      closePrice: 40,
      splitMultiplier: '1.00000',
      dividendAmount: '0.00000',
      weeklyAverageFinalPrice: 35,
      monthlyAverageFinalPrice: 33,
      quarterlyAverageFinalPrice: 31,
      yearlyAverageFinalPrice: 39,
      priceDailyIncrease: 2,
      priceDailyDecrease: 0,
      priceWeeklyIncrease: 2,
      priceWeeklyDecrease: 0,
      priceMonthlyIncrease: 3,
      priceMonthlyDecrease: 0,
      priceQuarterlyIncrease: 2,
      priceQuarterlyDecrease: 0,
      priceYearlyIncrease: 1,
      priceYearlyDecrease: 0,
    },
    {
      tickerId: 3,
      date: '2022-01-01',
      volume: '80000',
      closePrice: 1111,
      splitMultiplier: '1.00000',
      dividendAmount: '0.00000',
      weeklyAverageFinalPrice: 1111,
      monthlyAverageFinalPrice: 1112,
      quarterlyAverageFinalPrice: 1113,
      yearlyAverageFinalPrice: 1114,
      priceDailyIncrease: 0,
      priceDailyDecrease: 5,
      priceWeeklyIncrease: 0,
      priceWeeklyDecrease: 4,
      priceMonthlyIncrease: 0,
      priceMonthlyDecrease: 3,
      priceQuarterlyIncrease: 0,
      priceQuarterlyDecrease: 2,
      priceYearlyIncrease: 0,
      priceYearlyDecrease: 1,
    },
  ])
}

exports.down = () => {}
