exports.seed = (knex) => {
  return knex('trader').insert([
    {
      traderPatternId: 1,
      traderEnvId: 1,
      isActive: true, hasFollower: false,
      hasMutation: false,
      accessCode: '000',
      yearlyPercentNumber: 30,
      pastYearPercentNumber: 10,
      pastQuarterPercentNumber: 5,
      pastMonthPercentNumber: 20,
      pastWeekPercentNumber: 3,
      rankingNumber: 1,
    },
    {
      traderPatternId: 2,
      traderEnvId: 1,
      isActive: true, hasFollower: false,
      hasMutation: false,
      accessCode: '000',
      yearlyPercentNumber: 31,
      pastYearPercentNumber: 20,
      pastQuarterPercentNumber: 6,
      pastMonthPercentNumber: 19,
      pastWeekPercentNumber: 5,
      rankingNumber: 3,
    },
    {
      traderPatternId: 3,
      traderEnvId: 1,
      isActive: true, hasFollower: false,
      hasMutation: false,
      accessCode: '000',
      yearlyPercentNumber: 42,
      pastYearPercentNumber: 30,
      pastQuarterPercentNumber: 7,
      pastMonthPercentNumber: 18,
      pastWeekPercentNumber: 7,
      rankingNumber: 2,
    },
    {
      traderPatternId: 4,
      traderEnvId: 1,
      isActive: true, hasFollower: false,
      hasMutation: false,
      accessCode: '000',
      yearlyPercentNumber: 43,
      pastYearPercentNumber: 40,
      pastQuarterPercentNumber: 6,
      pastMonthPercentNumber: 17,
      pastWeekPercentNumber: 9,
    },
    {
      traderPatternId: 5,
      traderEnvId: 1,
      isActive: true, hasFollower: false,
      hasMutation: false,
      accessCode: '000',
      yearlyPercentNumber: 54,
      pastYearPercentNumber: 60,
      pastQuarterPercentNumber: 5,
      pastMonthPercentNumber: 16,
      pastWeekPercentNumber: 11,
    },
    {
      traderPatternId: 6,
      traderEnvId: 1,
      isActive: true, hasFollower: false,
      hasMutation: false,
      accessCode: '000',
      yearlyPercentNumber: 55,
      pastYearPercentNumber: 50,
      pastQuarterPercentNumber: 4,
      pastMonthPercentNumber: 15,
      pastWeekPercentNumber: 13,
    },
    { traderPatternId: 7, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 8, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 9, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 10, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 11, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 12, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 13, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 14, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 15, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 16, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 17, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 18, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 19, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 20, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 21, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 22, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 23, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 24, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 25, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 26, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 27, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 28, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 29, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 30, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 31, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 32, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 33, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 34, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 35, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 36, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 37, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 38, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 39, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 40, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 41, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 42, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 43, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 44, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 45, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 46, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 47, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 48, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 49, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 50, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 51, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 52, traderEnvId: 1, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    {
      traderPatternId: 1,
      traderEnvId: 2,
      isActive: true, hasFollower: false,
      hasMutation: false,
      accessCode: '000',
      yearlyPercentNumber: 51,
      pastYearPercentNumber: 50,
      pastQuarterPercentNumber: 36,
      pastMonthPercentNumber: 49,
      pastWeekPercentNumber: 35,
    },
    {
      traderPatternId: 2,
      traderEnvId: 2,
      isActive: true, hasFollower: false,
      hasMutation: false,
      accessCode: '000',
      yearlyPercentNumber: 36,
      pastYearPercentNumber: 25,
      pastQuarterPercentNumber: 11,
      pastMonthPercentNumber: 24,
      pastWeekPercentNumber: 9,
    },
    { traderPatternId: 3, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 4, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 5, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 6, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 7, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 8, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 9, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 10, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 11, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 12, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 13, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 14, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 15, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 16, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 17, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 18, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 19, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 20, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 21, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 22, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 23, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 24, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 25, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 26, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 27, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 28, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 29, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 30, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 31, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 32, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 33, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 34, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 35, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 36, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 37, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 38, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 39, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 40, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 41, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 42, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 43, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 44, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 45, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 46, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 47, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 48, traderEnvId: 2, isActive: true, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 49, traderEnvId: 2, isActive: false, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 50, traderEnvId: 2, isActive: false, hasFollower: false, hasMutation: false, accessCode: '000' },
    { traderPatternId: 51, traderEnvId: 2, isActive: false, hasFollower: false, hasMutation: false, accessCode: '000' },
    {
      traderPatternId: 52,
      traderEnvId: 2,
      isActive: false,
      hasFollower: false,
      hasMutation: false,
      accessCode: '000',
      totalValue: '12345',
      oneYearTrends: '100,101,102,103',
      oneDecadeTrends: '111,222,333,444',
    },
  ])
}

exports.down = () => {}
