exports.up = (knex) => {
  return knex('ticker').insert([
    { symbol: 'AAPL', region: 'US', name: 'Apple Inc.' },
    { symbol: 'MSFT', region: 'US', name: 'Microsoft Corp' },
    { symbol: 'AMZN', region: 'US', name: 'Amazon.com Inc.' },
    { symbol: 'GOOGL', region: 'US', name: 'Alphabet Inc. Class A' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc. Class C' },
    { symbol: 'FB', region: 'US', name: 'Meta Platforms Inc.' },
    { symbol: 'NFLX', region: 'US', name: 'Netflix Inc.' },
    { symbol: 'TSLA', region: 'US', name: 'Tesla Inc.' },
    { symbol: 'WMT', region: 'US', name: 'Walmart Inc.' },
    { symbol: 'AXP', region: 'US', name: 'American Express Co' },
    { symbol: 'AMGN', region: 'US', name: 'Amegen Inc.' },
    { symbol: 'BA', region: 'US', name: 'Boeing Co' },
    { symbol: 'CAT', region: 'US', name: 'Caterpillar Inc.' },
    { symbol: 'CSCO', region: 'US', name: 'Cisco Systems Inc.' },
    { symbol: 'CVX', region: 'US', name: 'Chevron Corp' },
    { symbol: 'GS', region: 'US', name: 'Goldman Sachs Group Inc.' },
    { symbol: 'HD', region: 'US', name: 'Home Depot Inc.' },
    { symbol: 'HON', region: 'US', name: 'Honeywell International Inc.' },
    { symbol: 'IBM', region: 'US', name: 'International Business Machines Corp' },
    { symbol: 'INTC', region: 'US', name: 'Intel Corp' },
    { symbol: 'JNJ', region: 'US', name: 'Johnson & Johnson' },
    { symbol: 'KO', region: 'US', name: 'Coca-Cola Co' },
    { symbol: 'JPM', region: 'US', name: 'JPMorgan Chase & Co' },
    { symbol: 'MCD', region: 'US', name: 'McDonald’s Corp' },
    { symbol: 'MMM', region: 'US', name: '3M Co' },
    { symbol: 'MRK', region: 'US', name: 'Merck & Co Inc.' },
    { symbol: 'NKE', region: 'US', name: 'Nike Inc.' },
    { symbol: 'PG', region: 'US', name: 'Procter & Gamble Co' },
    { symbol: 'TRV', region: 'US', name: 'Travelers Companies Inc.' },
    { symbol: 'UNH', region: 'US', name: 'UnitedHealth Group Inc.' },
    { symbol: 'CRM', region: 'US', name: 'Salesforce.Com Inc.' },
    { symbol: 'VZ', region: 'US', name: 'Verizon Communications Inc.' },
    { symbol: 'V', region: 'US', name: 'Visa Inc.' },
    { symbol: 'WBA', region: 'US', name: 'Walgreens Boots Alliance Inc.' },
    { symbol: 'DIS', region: 'US', name: 'Walt Disney Co' },
    { symbol: 'BB', region: 'US', name: 'BlackBerry Ltd' },
    { symbol: 'PYPL', region: 'US', name: 'Paypal Holdings Inc.' },
    { symbol: 'XOM', region: 'US', name: 'Exxon Mobile Corporation' },
    { symbol: 'PFE', region: 'US', name: 'Pfizer Inc.' },
    { symbol: 'ADBE', region: 'US', name: 'Adobe Inc.' },
    { symbol: 'MA', region: 'US', name: 'Mastercard Incorporated Class A' },
    { symbol: 'COST', region: 'US', name: 'Costco Wholesale Corporation' },
    { symbol: 'PEP', region: 'US', name: 'PepsiCo Inc.' },
    { symbol: 'WFC', region: 'US', name: 'Wells Fargo & Company' },
    { symbol: 'QCOM', region: 'US', name: 'Qualcomm Inc.' },
    { symbol: 'T', region: 'US', name: 'AT&T Inc.' },
    { symbol: 'AMD', region: 'US', name: 'Advanced Micro Devices Inc.' },
    { symbol: 'LOW', region: 'US', name: 'Lowe’s Companies Inc.' },
    { symbol: 'ORCL', region: 'US', name: 'Oracle Corporation' },
    { symbol: 'MS', region: 'US', name: 'Morgan Stanley' },
    { symbol: 'AMAT', region: 'US', name: 'Applied Materials Inc.' },
    { symbol: 'TGT', region: 'US', name: 'Target Corporation' },
    { symbol: 'DE', region: 'US', name: 'Deere & Company' },
    { symbol: 'COP', region: 'US', name: 'ConocoPhillips' },
    { symbol: 'GILD', region: 'US', name: 'Gilead Sciences Inc.' },
    { symbol: 'F', region: 'US', name: 'Ford Motor Company' },
    { symbol: 'ADSK', region: 'US', name: 'Autodesk Inc.' },
    { symbol: 'COF', region: 'US', name: 'Capital One Financial Corporation' },
    { symbol: 'TMUS', region: 'US', name: 'T-Mobile US Inc.' },
    { symbol: 'WM', region: 'US', name: 'Waste Management Inc.' },
    { symbol: 'FDX', region: 'US', name: 'FedEx Corporation' },
    { symbol: 'EBAY', region: 'US', name: 'eBay Inc.' },
    { symbol: 'MSI', region: 'US', name: 'Motorola Solutions Inc.' },
    { symbol: 'TWTR', region: 'US', name: 'Twitter Inc.' },
    { symbol: 'AWK', region: 'US', name: 'American Water Works Company Inc.' },
    { symbol: 'DLTR', region: 'US', name: 'Dollar Tree Inc.' },
    { symbol: 'DOV', region: 'US', name: 'Dover Corporation' },
    { symbol: 'XYL', region: 'US', name: 'Xylem Inc.' },
    { symbol: 'WAT', region: 'US', name: 'Waters Corporation' },
    { symbol: 'TRMB', region: 'US', name: 'Trimble Inc.' },
    { symbol: 'COO', region: 'US', name: 'Cooper Companies Inc.' },
    { symbol: 'DPZ', region: 'US', name: 'Domino’s Pizza Inc.' },
    { symbol: 'TDOC', region: 'US', name: 'Teladoc Health Inc.' },
    { symbol: 'COIN', region: 'US', name: 'Coinbase Global Inc. - Class A' },
    { symbol: 'U', region: 'US', name: 'Unity Software Inc.' },
    { symbol: 'ROKU', region: 'US', name: 'ROKU Inc.' },
    { symbol: 'ZM', region: 'US', name: 'Zoom' },
    { symbol: 'SHOP', region: 'US', name: 'Shopify Inc. - Class A' },
    { symbol: 'SPOT', region: 'US', name: 'Spotify Technology SA' },
    { symbol: 'SQ', region: 'US', name: 'Square Inc. - A' },
    { symbol: 'TWLO', region: 'US', name: 'Twilio Inc. - A' },
    { symbol: 'PATH', region: 'US', name: 'Uipath Inc. - Class A' },
    { symbol: 'EXAS', region: 'US', name: 'Exact Sciences Corp' },
    { symbol: 'NTLA', region: 'US', name: 'Intellia Therapeutics Inc.' },
    { symbol: 'PLTR', region: 'US', name: 'Palantir Technologies Inc. - A' },
    { symbol: 'BEAM', region: 'US', name: 'Beam Therapeutics Inc.' },
    { symbol: 'CRSP', region: 'US', name: 'Crispr Therapeutics AG' },
    { symbol: 'DOW', region: 'US', name: 'Dow Inc.' },
    { symbol: 'RTX', region: 'US', name: 'Taytheon Technologies Corporation' },
    { symbol: 'NVDA', region: 'US', name: 'Nvidia Corp' },
    { symbol: 'AVGO', region: 'US', name: 'Broadcom Inc.' },
    { symbol: 'CMCSA', region: 'US', name: 'Comcast Corp' },
    { symbol: 'TXN', region: 'US', name: 'Texas Instruments Inc.' },
    { symbol: 'INTU', region: 'US', name: 'Intuit Inc.' },
    { symbol: 'CHTR', region: 'US', name: 'Charter Communications Inc.' },
    { symbol: 'ISRG', region: 'US', name: 'Intuitive Surgical Inc.' },
    { symbol: 'SBUX', region: 'US', name: 'Starbucks Corp' },
    { symbol: 'ADP', region: 'US', name: 'Automatic Data Processing Inc.' },
    { symbol: 'MDLZ', region: 'US', name: 'Mondelez International Inc.' },
    { symbol: 'BKNG', region: 'US', name: 'Booking Holdings Inc.' },
    { symbol: 'ADI', region: 'US', name: 'Analog Devices Inc.' },
    { symbol: 'MU', region: 'US', name: 'Micron Technology Inc.' },
    { symbol: 'CSX', region: 'US', name: 'CSX Corp' },
    { symbol: 'REGN', region: 'US', name: 'Regeneron Pharmaceuticals' },
    { symbol: 'LRCX', region: 'US', name: 'Lam Research Corp' },
    { symbol: 'FISV', region: 'US', name: 'Fiserv Inc.' },
    { symbol: 'ATVI', region: 'US', name: 'Activision Blizzard Inc.' },
    { symbol: 'VRTX', region: 'US', name: 'Vertex Pharmaceuticals Inc.' },
    { symbol: 'MRNA', region: 'US', name: 'Moderna Inc.' },
    { symbol: 'MAR', region: 'US', name: 'Marriott International Inc./MD' },
    { symbol: 'KDP', region: 'US', name: 'Keurig Dr Pepper Inc.' },
    { symbol: 'PANW', region: 'US', name: 'Palo Alto Networks Inc.' },
    { symbol: 'MRVL', region: 'US', name: 'Marvell Technology Inc.' },
    { symbol: 'KLAC', region: 'US', name: 'KLA Corp' },
    { symbol: 'ABNB', region: 'US', name: 'Airbnb Inc.' },
    { symbol: 'ILMN', region: 'US', name: 'Illumina Inc.' },
    { symbol: 'AEP', region: 'US', name: 'American Electric Power Co Inc.' },
    { symbol: 'ASML', region: 'US', name: 'ASML Holding NV' },
    { symbol: 'KHC', region: 'US', name: 'Kraft Heinz Co/The' },
    { symbol: 'CTSH', region: 'US', name: 'Cognizant Technology' },
    { symbol: 'NXPI', region: 'US', name: 'NXP Semiconductors NV' },
    { symbol: 'ORLY', region: 'US', name: 'O’Reilly Automotive Inc.' },
    { symbol: 'FTNT', region: 'US', name: 'Fortinet Inc.' },
    { symbol: 'MELI', region: 'US', name: 'MercadoLibre Inc.' },
    { symbol: 'PAYX', region: 'US', name: 'Paychex Inc.' },
    { symbol: 'WDAY', region: 'US', name: 'Workday Inc.' },
    { symbol: 'EXC', region: 'US', name: 'Exelon Corp' },
    { symbol: 'SNPS', region: 'US', name: 'Synopsys Inc.' },
    { symbol: 'IDXX', region: 'US', name: 'IDEXX Laboratories Inc.' },
    { symbol: 'DXCM', region: 'US', name: 'Dexcom Inc.' },
    { symbol: 'CTAS', region: 'US', name: 'Cintas Corp' },
    { symbol: 'MNST', region: 'US', name: 'Monster Beverage Corp' },
    { symbol: 'CDNS', region: 'US', name: 'Cadence Design Systems Inc.' },
    { symbol: 'MCHP', region: 'US', name: 'Microchip Technology Inc.' },
    { symbol: 'CRWD', region: 'US', name: 'Crowdstrike Holdings Inc.' },
    { symbol: 'XEL', region: 'US', name: 'Xcel Energe Inc.' },
    { symbol: 'LULU', region: 'US', name: 'Lululemon Athletica Inc.' },
    { symbol: 'AZN', region: 'US', name: 'AstraZeneca PLC ADR' },
    { symbol: 'LCID', region: 'US', name: 'Lucid Group Inc.' },
    { symbol: 'ODFL', region: 'US', name: 'Old Dominion Feight Line Inc.' },
    { symbol: 'EA', region: 'US', name: 'Electronic Arts Inc.' },
    { symbol: 'TEAM', region: 'US', name: 'Atlassian Corp PLC' },
    { symbol: 'JD', region: 'US', name: 'JD.com Inc. ADR' },
    { symbol: 'FAST', region: 'US', name: 'Fastenal Co' },
    { symbol: 'DDOG', region: 'US', name: 'Datadog Inc.' },
    { symbol: 'ROST', region: 'US', name: 'Ross Stores Inc.' },
    { symbol: 'PCAR', region: 'US', name: 'PACCAR Inc.' },
    { symbol: 'VRSK', region: 'US', name: 'Verisk Analytics Inc.' },
    { symbol: 'ALGN', region: 'US', name: 'Align Technology Inc.' },
    { symbol: 'BIIB', region: 'US', name: 'Biogen Inc.' },
    { symbol: 'CPRT', region: 'US', name: 'Copart Inc.' },
    { symbol: 'ZS', region: 'US', name: 'Zscaler Inc.' },
    { symbol: 'BIDU', region: 'US', name: 'Baidu Inc. ADR' },
    { symbol: 'ANSS', region: 'US', name: 'ANSYS Inc.' },
    { symbol: 'SGEN', region: 'US', name: 'Seagen Inc.' },
    { symbol: 'SIRI', region: 'US', name: 'Sirius XM Holdings Inc.' },
    { symbol: 'VRSN', region: 'US', name: 'VeriSign Inc.' },
    { symbol: 'OKTA', region: 'US', name: 'Okta Inc.' },
    { symbol: 'NTES', region: 'US', name: 'NetEase Inc. ADR' },
    { symbol: 'SWKS', region: 'US', name: 'Skyworks Solutions Inc.' },
    { symbol: 'SPLK', region: 'US', name: 'Splunk Inc.' },
    { symbol: 'CEG', region: 'US', name: 'Constellation Energe Corp' },
    { symbol: 'DOCU', region: 'US', name: 'DocuSign Inc.' },
    { symbol: 'PDD', region: 'US', name: 'pinduoduo Inc. ADR' },
    { symbol: 'BRK.B', region: 'US', name: 'Berkshire Hathaway Inc.' },
    { symbol: 'BAC', region: 'US', name: 'Bank of America Corp' },
    { symbol: 'ABBV', region: 'US', name: 'AbbVie Inc.' },
    { symbol: 'TMO', region: 'US', name: 'Thermo Fisher Scientific Inc.' },
    { symbol: 'LLY', region: 'US', name: 'Eli Lilly and Company' },
    { symbol: 'ABT', region: 'US', name: 'Abbott Laboratories' },
    { symbol: 'ACN', region: 'US', name: 'Accenture Plc Class A' },
    { symbol: 'DHR', region: 'US', name: 'Danaher Corporation' },
    { symbol: 'UNP', region: 'US', name: 'Union Pacific Corporation' },
    { symbol: 'NEE', region: 'US', name: 'NextEra Energe Inc.' },
    { symbol: 'UPS', region: 'US', name: 'United Parcel Service Inc. Class B' },
    { symbol: 'LIN', region: 'US', name: 'Linde plc' },
    { symbol: 'BMY', region: 'US', name: 'Bristol-Myers Squibb Company' },
    { symbol: 'PM', region: 'US', name: 'Philip Morris International Inc.' },
    { symbol: 'MDT', region: 'US', name: 'Medtronic Plc' },
    { symbol: 'CVS', region: 'US', name: 'CBS Health Corporation' },
    { symbol: 'SPGI', region: 'US', name: 'S&P Global Inc.' },
    { symbol: 'SCHW', region: 'US', name: 'Charles Schwab Corp' },
    { symbol: 'ANTM', region: 'US', name: 'Anthem Inc.' },
    { symbol: 'PLD', region: 'US', name: 'Prologis Inc.' },
    { symbol: 'C', region: 'US', name: 'Citigroup Inc.' },
    { symbol: 'NOW', region: 'US', name: 'ServiceNow Inc.' },
    { symbol: 'AMT', region: 'US', name: 'American Tower Corporation' },
    { symbol: 'BLK', region: 'US', name: 'BlackRock Inc.' },
    { symbol: 'GE', region: 'US', name: 'General Electric Company' },
    { symbol: 'LMT', region: 'US', name: 'Lockheed Martin Corporation' },
    { symbol: 'MO', region: 'US', name: 'Altria Group Inc.' },
    { symbol: 'CB', region: 'US', name: 'Chubb Limited' },
    { symbol: 'ZTS', region: 'US', name: 'Zoetis Inc. Class A' },
    { symbol: 'SYK', region: 'US', name: 'Stryker Corporation' },
    { symbol: 'CME', region: 'US', name: 'CME Group Inc. Class A' },
    { symbol: 'DUK', region: 'US', name: 'Duke Energy Corporation' },
    { symbol: 'PNC', region: 'US', name: 'PNC Financial Services Group Inc.' },
    { symbol: 'MMC', region: 'US', name: 'Marsh & McLennan Companies Inc.' },
    { symbol: 'TFC', region: 'US', name: 'Truist Financial Corporation' },
    { symbol: 'CI', region: 'US', name: 'Cigna Corporation' },
    { symbol: 'USB', region: 'US', name: 'U.S. Bancorp' },
    { symbol: 'TJX', region: 'US', name: 'TJX Companies Inc.' },
    { symbol: 'CCI', region: 'US', name: 'Crown Castle International Corp' },
    { symbol: 'BDX', region: 'US', name: 'Becton Dickinson and Company' },
    { symbol: 'ICE', region: 'US', name: 'Intercontinental Exchange Inc.' },
    { symbol: 'SO', region: 'US', name: 'Southern COmpany' },
    { symbol: 'EW', region: 'US', name: 'Edwards Lifesciences Corporation' },
    { symbol: 'AON', region: 'US', name: 'Aon Plc Class A' },
    { symbol: 'FCX', region: 'US', name: 'Freeport-McMoRan Inc.' },
    { symbol: 'NSC', region: 'US', name: 'Norfolk Southern Corporation' },
    { symbol: 'EOG', region: 'US', name: 'EOG Resources Inc.' },
    { symbol: 'D', region: 'US', name: 'Dominion Energy Inc.' },
    { symbol: 'HCA', region: 'US', name: 'HCA Healthcare Inc.' },
    { symbol: 'GM', region: 'US', name: 'General Motors Company' },
    { symbol: 'CL', region: 'US', name: 'Colgate-Palmolive Company' },
    { symbol: 'NOC', region: 'US', name: 'Northrop Grumman Corporation' },
    { symbol: 'EQIX', region: 'US', name: 'Equinix Inc.' },
    { symbol: 'EL', region: 'US', name: 'Estee Lauder Companies Inc. Class A' },
    { symbol: 'BSX', region: 'US', name: 'Boston Scientific Corporation' },
    { symbol: 'PGR', region: 'US', name: 'Progressive Corporation' },
    { symbol: 'ETN', region: 'US', name: 'Eaton Corp Plc' },
    { symbol: 'ITW', region: 'US', name: 'Illinois Tool Works Inc.' },
    { symbol: 'SHW', region: 'US', name: 'Sherwin-Williams Company' },
    { symbol: 'FIS', region: 'US', name: 'Fidelity National Information Services Inc.' },
    { symbol: 'NEM', region: 'US', name: 'Newmont Corporation' },
    { symbol: 'HUM', region: 'US', name: 'Humana Inc.' },
    { symbol: 'EMR', region: 'US', name: 'Emerson Electric Co' },
    { symbol: 'PSA', region: 'US', name: 'Public Storage' },
    { symbol: 'SLB', region: 'US', name: 'Schlumberger NV' },
    { symbol: 'GD', region: 'US', name: 'General Dynamics Corporation' },
    { symbol: 'PXD', region: 'US', name: 'Pioneer Natural Resources Company' },
    { symbol: 'MCO', region: 'US', name: 'Moody’s Corporation' },
    { symbol: 'CNC', region: 'US', name: 'Centene Corporation' },
    { symbol: 'AIG', region: 'US', name: 'American International Group Inc.' },
    { symbol: 'DG', region: 'US', name: 'Dollar General Corporation' },
    { symbol: 'SRE', region: 'US', name: 'Sempra Energy' },
    { symbol: 'MET', region: 'US', name: 'MetLife Inc.' },
    { symbol: 'LHX', region: 'US', name: 'L3Harris Technologies Inc.' },
    { symbol: 'ROP', region: 'US', name: 'Roper Technologies Inc.' },
    { symbol: 'OXY', region: 'US', name: 'Occidental Petroleum Corporation' },
    { symbol: 'MPC', region: 'US', name: 'Marathon Petroleum Corporation' },
    { symbol: 'JCI', region: 'US', name: 'Johnson Controls INternational plc' },
    { symbol: 'ADM', region: 'US', name: 'Archer-Daniels-Midland Company' },
    { symbol: 'APH', region: 'US', name: 'Amphenol Corporation Class A' },
    { symbol: 'MCK', region: 'US', name: 'McKesson Corporation' },
    { symbol: 'CMG', region: 'US', name: 'Chipotle Mexican Grill Inc.' },
    { symbol: 'SPG', region: 'US', name: 'Simon Property Group Inc.' },
    { symbol: 'PRU', region: 'US', name: 'Prudential Financial Inc.' },
    { symbol: 'TEL', region: 'US', name: 'TE Connectivity Ltd.' },
    { symbol: 'ECL', region: 'US', name: 'Ecolab Inc.' },
    { symbol: 'IQV', region: 'US', name: 'IQVIA Holdings Inc.' },
    { symbol: 'HLT', region: 'US', name: 'Hilton Worldwide Holdings Inc.' },
    { symbol: 'AZO', region: 'US', name: 'AutoZone Inc.' },
    { symbol: 'HPQ', region: 'US', name: 'HP Inc.' },
    { symbol: 'A', region: 'US', name: 'Agilent Technologies Inc.' },
    { symbol: 'SYY', region: 'US', name: 'Sysco Corporation' },
    { symbol: 'KMB', region: 'US', name: 'Kimberly-Clark Corporation' },
    { symbol: 'CARR', region: 'US', name: 'Carrier Global Corp.' },
    { symbol: 'MSCI', region: 'US', name: 'MSCI Inc. Class A' },
    { symbol: 'CTVA', region: 'US', name: 'Corteva Inc.' },
    { symbol: 'WELL', region: 'US', name: 'Welltower Inc.' },
    { symbol: 'BK', region: 'US', name: 'Bank of New York Mellon Corporation' },
    { symbol: 'BAX', region: 'US', name: 'Baxter International Inc.' },
    { symbol: 'GPN', region: 'US', name: 'Global Payments Inc.' },
    { symbol: 'NUE', region: 'US', name: 'Nucor Corporation' },
    { symbol: 'DD', region: 'US', name: 'Dupont de Nemours Inc.' },
    { symbol: 'DLR', region: 'US', name: 'Digital Realty Trust Inc.' },
    { symbol: 'AFL', region: 'US', name: 'Aflac Incorporated' },
    { symbol: 'GIS', region: 'US', name: 'General Mills Inc.' },
    { symbol: 'WMB', region: 'US', name: 'Williams Companies Inc.' },
    { symbol: 'KR', region: 'US', name: 'Kroger Co' },
    { symbol: 'O', region: 'US', name: 'Realty Income Corporation' },
    { symbol: 'TT', region: 'US', name: 'Trane Technologies plc' },
    { symbol: 'RMD', region: 'US', name: 'ResMed Inc.' },
    { symbol: 'PH', region: 'US', name: 'Parker-Hannifin Corporation' },
    { symbol: 'STZ', region: 'US', name: 'Constellation Brands Inc. Class A' },
    { symbol: 'ALL', region: 'US', name: 'Allstate Corporation' },
    { symbol: 'PSX', region: 'US', name: 'Phillips 66' },
    { symbol: 'SBAC', region: 'US', name: 'SBA Comminications Corp Class A' },
    { symbol: 'YUM', region: 'US', name: 'Yum! Brands Inc.' },
    { symbol: 'VLO', region: 'US', name: 'Valero Energy Corporation' },
    { symbol: 'TDG', region: 'US', name: 'TransDigm Group Incorporated' },
    { symbol: 'PEG', region: 'US', name: 'Public Service Enterprise Group Inc.' },
    { symbol: 'AVB', region: 'US', name: 'AvalonBay Communities Inc.' },
    { symbol: 'KMI', region: 'US', name: 'Kinder Morgan Inc. Class P' },
    { symbol: 'AJG', region: 'US', name: 'Arthur J. Gallapher & Co.' },
    { symbol: 'DFS', region: 'US', name: 'Discover Financial Services' },
    { symbol: 'DVN', region: 'US', name: 'Devon Energy Corporation' },
    { symbol: 'AMP', region: 'US', name: 'Ameriprise Financial Inc.' },
    { symbol: 'TROW', region: 'US', name: 'T. Rowe Price Group' },
    { symbol: 'SIVB', region: 'US', name: 'SVB FInancial Group' },
    { symbol: 'FITB', region: 'US', name: 'Fifth Third Bancorp' },
    { symbol: 'OTIS', region: 'US', name: 'Otis Worldwode Corporation' },
    { symbol: 'STT', region: 'US', name: 'State Street Corporation' },
    { symbol: 'IFF', region: 'US', name: 'International Flavors & Fragrances Inc.' },
    { symbol: 'ED', region: 'US', name: 'Consolidated Edison Inc.' },
    { symbol: 'APTV', region: 'US', name: 'Aptiv PLC' },
    { symbol: 'MTD', region: 'US', name: 'Mettler-Toledo International Inc.' },
    { symbol: 'ROK', region: 'US', name: 'Rockwell Automation Inc.' },
    { symbol: 'CBRE', region: 'US', name: 'CBRE Group Inc. Class A' },
    { symbol: 'FRC', region: 'US', name: 'First Republic Bank' },
    { symbol: 'AME', region: 'US', name: 'AMETEK Inc.' },
    { symbol: 'PPG', region: 'US', name: 'PPG Industries Inc.' },
    { symbol: 'HAL', region: 'US', name: 'Halliburton Company' },
    { symbol: 'EQR', region: 'US', name: 'Equity Residential' },
    { symbol: 'HSY', region: 'US', name: 'Hershey Company' },
    { symbol: 'WEC', region: 'US', name: 'WEC Energy Group Inc.' },
    { symbol: 'BLL', region: 'US', name: 'Ball Corporation' },
    { symbol: 'CMI', region: 'US', name: 'Cummins Inc.' },
    { symbol: 'BKR', region: 'US', name: 'Baker Hughes Company Class A' },
    { symbol: 'WY', region: 'US', name: 'Weyerhaeuser Company' },
    { symbol: 'WST', region: 'US', name: 'West Pharmaceutical' },
    { symbol: 'ES', region: 'US', name: 'Eversource Energy' },
    { symbol: 'OKE', region: 'US', name: 'ONEOK Inc.' },
    { symbol: 'WTW', region: 'US', name: 'Willis Towers Watson Public Limited Company' },
    { symbol: 'GLW', region: 'US', name: 'Corning Inc.' },
    { symbol: 'EFX', region: 'US', name: 'Equifax Inc.' },
    { symbol: 'KEYS', region: 'US', name: 'Keysight Technologies Inc.' },
    { symbol: 'EXPE', region: 'US', name: 'Expedia Group Inc.' },
    { symbol: 'ANET', region: 'US', name: 'Arista Network Inc.' },
    { symbol: 'Cern', region: 'US', name: 'Cerner Corporation' },
    { symbol: 'RSG', region: 'US', name: 'Republic Services Inc.' },
    { symbol: 'ARE', region: 'US', name: 'Alexandria Real Estate Equities Inc.' },
    { symbol: 'DHI', region: 'US', name: 'D.R. Horton Inc.' },
    { symbol: 'LH', region: 'US', name: 'Laboratory Corporation of America Holdings' },
    { symbol: 'MTCH', region: 'US', name: 'Match Group Inc.' },
    { symbol: 'LYB', region: 'US', name: 'LyondellBasell Industries NV' },
    { symbol: 'HES', region: 'US', name: 'Hess Corporation' },
    { symbol: 'TSCO', region: 'US', name: 'Tractor Supply Company' },
    { symbol: 'EXR', region: 'US', name: 'Extra Space Storage Inc.' },
    { symbol: 'TSN', region: 'US', name: 'Tyson Foods Inc. Class A' },
    { symbol: 'LUV', region: 'US', name: 'Southwest Airlines Co' },
    { symbol: 'ZBH', region: 'US', name: 'Zimmer Biomet Holdings Inc.' },
    { symbol: 'EIX', region: 'US', name: 'Edison International' },
    { symbol: 'DTE', region: 'US', name: 'DTE Energy Company' },
    { symbol: 'URI', region: 'US', name: 'United Rentals Inc.' },
    { symbol: 'LEN', region: 'US', name: 'Lennar Corporation Class A' },
    { symbol: 'NTRS', region: 'US', name: 'Northen Trust Corporation' },
    { symbol: 'MKC', region: 'US', name: 'McCormick & Company Incorporated' },
    { symbol: 'VMC', region: 'US', name: 'Vulcan Materials Company' },
    { symbol: 'SWK', region: 'US', name: 'Stanley Black & Decker Inc.' },
    { symbol: 'IT', region: 'US', name: 'Gartner Inc.' },
    { symbol: 'MAA', region: 'US', name: 'Mid-America Apartment Communities Inc.' },
    { symbol: 'FE', region: 'US', name: 'FirstEnergy Inc.' },
    { symbol: 'ENPH', region: 'US', name: 'Enphase Energy Inc.' },
    { symbol: 'CHD', region: 'US', name: 'Church & Dwight Co. Inc.' },
    { symbol: 'HIG', region: 'US', name: 'Hartford Financial Services Group Inc.' },
    { symbol: 'MLM', region: 'US', name: 'Martin Marietta Materials Inc.' },
    { symbol: 'DAL', region: 'US', name: 'Delta Air Lines Inc.' },
    { symbol: 'CDW', region: 'US', name: 'CDW Corp.' },
    { symbol: 'VTR', region: 'US', name: 'Ventas Inc.' },
    { symbol: 'MTB', region: 'US', name: 'M&T Bank Corporation' },
    { symbol: 'KEY', region: 'US', name: 'KeyCorp' },
    { symbol: 'AEE', region: 'US', name: 'Ameren Corporation' },
    { symbol: 'RF', region: 'US', name: 'Regions Financial Corporation' },
    { symbol: 'ALB', region: 'US', name: 'Alemarle Corporation' },
    { symbol: 'HBAN', region: 'US', name: 'Huntington Banschares Incorporated' },
    { symbol: 'ABC', region: 'US', name: 'AmerisourceBergen Corporation' },
    { symbol: 'STE', region: 'US', name: 'STERIS Plc' },
    { symbol: 'PKI', region: 'US', name: 'PerkinElmer Inc.' },
    { symbol: 'ESS', region: 'US', name: 'Essex Property Trust Inc.' },
    { symbol: 'ETR', region: 'US', name: 'Entergy Corporation' },
    { symbol: 'PARA', region: 'US', name: 'Paramount Global Class B' },
    { symbol: 'BBY', region: 'US', name: 'Best Buy Co. Inc.' },
    { symbol: 'HPE', region: 'US', name: 'Hewlett Packard Enterprise Co.' },
    { symbol: 'GWW', region: 'US', name: 'W.W. Grainger Inc.' },
    { symbol: 'ZBRA', region: 'US', name: 'Zebra Technologies Corporation Class A' },
    { symbol: 'CFG', region: 'US', name: 'Citizens Financial Group Inc.' },
    { symbol: 'FANG', region: 'US', name: 'Diamondback Energy Inc.' },
    { symbol: 'MOS', region: 'US', name: 'Mosaic Company' },
    { symbol: 'FTV', region: 'US', name: 'Fortive Corp' },
    { symbol: 'ULTA', region: 'US', name: 'Ulta Beauty Inc.' },
    { symbol: 'DRE', region: 'US', name: 'Duke Realty Corporation' },
    { symbol: 'SYF', region: 'US', name: 'Synchrony Financial' },
    { symbol: 'IR', region: 'US', name: 'ingersoll Rand Inc.' },
    { symbol: 'PPL', region: 'US', name: 'PPL Corporation' },
    { symbol: 'NDAQ', region: 'US', name: 'Nasdaq Inc.' },
    { symbol: 'TDY', region: 'US', name: 'Teledyne Technologies Incorporated' },
    { symbol: 'CINF', region: 'US', name: 'Cincinnati Financial Corporation' },
    { symbol: 'SBNY', region: 'US', name: 'Signature Bank' },
    { symbol: 'MOH', region: 'US', name: 'Molina Healthcare Inc.' },
    { symbol: 'CMS', region: 'US', name: 'CMS Energy Corporation' },
    { symbol: 'GNRC', region: 'US', name: 'Generac Holdings Inc.' },
    { symbol: 'RJF', region: 'US', name: 'Raymond James Financial' },
    { symbol: 'FLT', region: 'US', name: 'FLEETCOR Technologies Inc.' },
    { symbol: 'TER', region: 'US', name: 'Teradyne Inc.' },
    { symbol: 'CTRA', region: 'US', name: 'Coterra Energy Inc.' },
    { symbol: 'NTAP', region: 'US', name: 'NetApp Inc.' },
    { symbol: 'CF', region: 'US', name: 'CF Industries Holdings Inc.' },
    { symbol: 'MPWR', region: 'US', name: 'Monolithic Power System Inc.' },
    { symbol: 'POOL', region: 'US', name: 'Pool Corporation' },
    { symbol: 'HOLX', region: 'US', name: 'Hologic Inc.' },
    { symbol: 'JBHT', region: 'US', name: 'J.B. Hunt Transport Services Inc.' },
    { symbol: 'AKAM', region: 'US', name: 'Akamai Technologies Inc.' },
    { symbol: 'GPC', region: 'US', name: 'Genuine Parts Company' },
    { symbol: 'VFC', region: 'US', name: 'V.F. Corporation' },
    { symbol: 'CNP', region: 'US', name: 'CenterPoint Energy Inc.' },
    { symbol: 'STX', region: 'US', name: 'Seagate Technology Holdings PLC' },
    { symbol: 'OMC', region: 'US', name: 'Omnicom Group Inc.' },
    { symbol: 'PEAK', region: 'US', name: 'Healthpeak Properties Inc.' },
    { symbol: 'WAB', region: 'US', name: 'Westinghouse Air Brake Technologies Corporation' },
    { symbol: 'AMCR', region: 'US', name: 'Amcor PLC' },
    { symbol: 'J', region: 'US', name: 'Jacobs Engineering Group Inc.' },
    { symbol: 'SEDG', region: 'US', name: 'SolarEdge Technologies Inc.' },
    { symbol: 'BXP', region: 'US', name: 'Boston Properties Inc.' },
    { symbol: 'BR', region: 'US', name: 'Broadridge Financial Solutions Inc.' },
    { symbol: 'CTLT', region: 'US', name: 'Catalent Inc.' },
    { symbol: 'DGX', region: 'US', name: 'Quest Diagnostics Incorporated' },
    { symbol: 'EXPD', region: 'US', name: 'Expeditors International of Washington Inc.' },
    { symbol: 'PFG', region: 'US', name: 'Principal Financial Group Inc.' },
    { symbol: 'TTWO', region: 'US', name: 'Take-Two Interactive Software Inc.' },
    { symbol: 'IP', region: 'US', name: 'International Paper Company' },
    { symbol: 'PWR', region: 'US', name: 'Quanta Services Inc.' },
    { symbol: 'MRO', region: 'US', name: 'Marathon Oil Corporation' },
    { symbol: 'ETSY', region: 'US', name: 'Etsy Inc.' },
    { symbol: 'TYL', region: 'US', name: 'Tyler Technologies Inc.' },
    { symbol: 'DRI', region: 'US', name: 'Darden Restaurants Inc.' },
    { symbol: 'GRMN', region: 'US', name: 'Garmin Ltd.' },
    { symbol: 'MGM', region: 'US', name: 'MGM Resorts International' },
    { symbol: 'CZR', region: 'US', name: 'Caesars Entertainment Inc.' },
    { symbol: 'KMX', region: 'US', name: 'CarMax Inc.' },
    { symbol: 'UDR', region: 'US', name: 'UDR Inc.' },
    { symbol: 'TECH', region: 'US', name: 'Bio-Techne Corporation' },
    { symbol: 'RCL', region: 'US', name: 'Royal Caribbean Group' },
    { symbol: 'FMC', region: 'US', name: 'FMC Corporation' },
    { symbol: 'TXT', region: 'US', name: 'Textron Inc.' },
    { symbol: 'CLX', region: 'US', name: 'Clorox Company' },
    { symbol: 'EPAM', region: 'US', name: 'EPAM Systems Inc.' },
    { symbol: 'TFX', region: 'US', name: 'Teleflex Incorporated' },
    { symbol: 'NVR', region: 'US', name: 'NVR Inc.' },
    { symbol: 'FDS', region: 'US', name: 'FactSet Research Systems Inc.' },
    { symbol: 'PAYC', region: 'US', name: 'Paycom Software Inc.' },
    { symbol: 'BRO', region: 'US', name: 'Brown & Brown Inc.' },
    { symbol: 'CE', region: 'US', name: 'Celanese Corporation' },
    { symbol: 'K', region: 'US', name: 'Kellogg Company' },
    { symbol: 'CCL', region: 'US', name: 'Carnival Corporation' },
    { symbol: 'LNT', region: 'US', name: 'Alliant Energe Corp' },
    { symbol: 'CAG', region: 'US', name: 'Conagra Brands Inc.' },
    { symbol: 'CAH', region: 'US', name: 'Cardinal Health Inc.' },
    { symbol: 'NLOK', region: 'US', name: 'NortonLifeLock Inc.' },
    { symbol: 'AES', region: 'US', name: 'AES Corporation' },
    { symbol: 'ATO', region: 'US', name: 'Atmos Energy Corporation' },
    { symbol: 'IEX', region: 'US', name: 'IDEX Corporation' },
    { symbol: 'EVRG', region: 'US', name: 'Evergy Inc.' },
    { symbol: 'WDC', region: 'US', name: 'Western Digital Corporation' },
    { symbol: 'PKG', region: 'US', name: 'Packaging Corporation of America' },
    { symbol: 'LYV', region: 'US', name: 'Live Nation Entertainment Inc.' },
    { symbol: 'EMN', region: 'US', name: 'Eastman Chemical Company' },
    { symbol: 'KIM', region: 'US', name: 'Kimco Realty Corporation' },
    { symbol: 'LDOS', region: 'US', name: 'Leidos Holdings Inc.' },
    { symbol: 'IRM', region: 'US', name: 'Iron Mountain Inc.' },
    { symbol: 'IPG', region: 'US', name: 'Interpublic Group of Companies Inc.' },
    { symbol: 'QRVO', region: 'US', name: 'Qorvo Inc.' },
    { symbol: 'AVY', region: 'US', name: 'Avery Dennison Corporation' },
    { symbol: 'INCY', region: 'US', name: 'Incyte Corporation' },
    { symbol: 'SJM', region: 'US', name: 'J.M. Smucker Company' },
    { symbol: 'HRL', region: 'US', name: 'Hormel Foods Corporation' },
    { symbol: 'MAS', region: 'US', name: 'Masco Corporation' },
    { symbol: 'JKHY', region: 'US', name: 'Jack Henry & Associates Inc.' },
    { symbol: 'CRL', region: 'US', name: 'Charles RIver Laboratories International Inc.' },
    { symbol: 'HWM', region: 'US', name: 'Howmet Aerospace Inc.' },
    { symbol: 'MKTX', region: 'US', name: 'MarketAxess Holdings Inc.' },
    { symbol: 'CHRW', region: 'US', name: 'C.H. Robinson Worldwide Inc.' },
    { symbol: 'APA', region: 'US', name: 'APA Corp' },
    { symbol: 'HST', region: 'US', name: 'Host Hotels & Resorts Inc.' },
    { symbol: 'ABMD', region: 'US', name: 'ABIOMED Inc.' },
    { symbol: 'AAP', region: 'US', name: 'Advance Auto Partes Inc.' },
    { symbol: 'UAL', region: 'US', name: 'United Airlines Holdings Inc.' },
    { symbol: 'WRB', region: 'US', name: 'W. R. Berkley Corporation' },
    { symbol: 'FOXA', region: 'US', name: 'Fox Corporation Class A' },
    { symbol: 'RHI', region: 'US', name: 'Robert Half International Inc.' },
    { symbol: 'L', region: 'US', name: 'Loews Corporation' },
    { symbol: 'BBWI', region: 'US', name: 'Bath & Body Works Inc.' },
    { symbol: 'CMA', region: 'US', name: 'Comerica Incorporated' },
    { symbol: 'LKQ', region: 'US', name: 'LKQ Corporation' },
    { symbol: 'WRK', region: 'US', name: 'WestRock Company' },
    { symbol: 'VTRS', region: 'US', name: 'Viatris Inc.' },
    { symbol: 'CTXS', region: 'US', name: 'Citrix Systems Inc.' },
    { symbol: 'CBOE', region: 'US', name: 'Cboe Global Markets Inc.' },
    { symbol: 'NDSN', region: 'US', name: 'Nordson Corporation' },
    { symbol: 'BIO', region: 'US', name: 'Bio-Rad Laboratories Inc. Class A' },
    { symbol: 'LVS', region: 'US', name: 'Las Vegas Sands Corp' },
    { symbol: 'HSIC', region: 'US', name: 'Henry Schein Inc.' },
    { symbol: 'FFIV', region: 'US', name: 'F5 Inc.' },
    { symbol: 'PHM', region: 'US', name: 'PulteGroup Inc.' },
    { symbol: 'FBHS', region: 'US', name: 'Fortune Brands Home & Security Inc.' },
    { symbol: 'WHR', region: 'US', name: 'Whirlpool Corporation' },
    { symbol: 'NI', region: 'US', name: 'NiSource Inc.' },
    { symbol: 'BF.B', region: 'US', name: 'Brown-Forman Corporation Class B' },
    { symbol: 'PTC', region: 'US', name: 'PTC Inc.' },
    { symbol: 'HAS', region: 'US', name: 'Hasbro Inc.' },
    { symbol: 'RE', region: 'US', name: 'Everest Re Group Ltd.' },
    { symbol: 'LNC', region: 'US', name: 'Lincoln National Corporation' },
    { symbol: 'SNA', region: 'US', name: 'Snap-on Incorporated' },
    { symbol: 'JNPR', region: 'US', name: 'Juniper Networks Inc.' },
    { symbol: 'Zion', region: 'US', name: 'Zions Bancorporation N.A.' },
    { symbol: 'UHS', region: 'US', name: 'Universal Health Services Inc. Class B' },
    { symbol: 'AAL', region: 'US', name: 'American Airlines Group Inc.' },
    { symbol: 'XRAY', region: 'US', name: 'DENTSPLY SIRONA Inc.' },
    { symbol: 'ALLE', region: 'US', name: 'Allegion PLC' },
    { symbol: 'TPR', region: 'US', name: 'Tapestry Inc.' },
    { symbol: 'REG', region: 'US', name: 'Regency Centers Corporation' },
    { symbol: 'SEE', region: 'US', name: 'Sealed Air Corporation' },
    { symbol: 'LUMN', region: 'US', name: 'Lumen Technologies Inc.' },
    { symbol: 'AIZ', region: 'US', name: 'Assurant Inc.' },
    { symbol: 'TAP', region: 'US', name: 'Molson Coors Beverage Company Class B' },
    { symbol: 'NRG', region: 'US', name: 'NRG Energy Inc.' },
    { symbol: 'PNR', region: 'US', name: 'Pentair plc' },
    { symbol: 'GL', region: 'US', name: 'Globe Life Inc.' },
    { symbol: 'BWA', region: 'US', name: 'BorgWarner Inc.' },
    { symbol: 'PBCT', region: 'US', name: 'People’s United Financial Inc.' },
    { symbol: 'AOS', region: 'US', name: 'A. O. Smith Corporation' },
    { symbol: 'CPB', region: 'US', name: 'Campbell Soup Company' },
    { symbol: 'CDAY', region: 'US', name: 'Ceridian HCM Holding Inc.' },
    { symbol: 'NWL', region: 'US', name: 'Newell Brands Inc.' },
    { symbol: 'NWSA', region: 'US', name: 'News Corporation Class A' },
    { symbol: 'NLSN', region: 'US', name: 'Nielsen Holdings Plc' },
    { symbol: 'PNW', region: 'US', name: 'Pinnacle West Capital Corporation' },
    { symbol: 'OGN', region: 'US', name: 'Organon & Co.' },
    { symbol: 'DXC', region: 'US', name: 'DXC Technology Co.' },
    { symbol: 'FRT', region: 'US', name: 'Federal Realty Investment Trust' },
    { symbol: 'MHK', region: 'US', name: 'Mohawk Industries Inc.' },
    { symbol: 'WYNN', region: 'US', name: 'Wynn Resorts Limited' },
    { symbol: 'HII', region: 'US', name: 'Huntington Ingalls Industries Inc.' },
    { symbol: 'LW', region: 'US', name: 'Lamb Weston Holdings Inc.' },
    { symbol: 'DISH', region: 'US', name: 'DISH Network Corporation Class A' },
    { symbol: 'BEN', region: 'US', name: 'Franklin Resources Inc.' },
    { symbol: 'DVA', region: 'US', name: 'DaVita Inc.' },
    { symbol: 'ROL', region: 'US', name: 'Rollins Inc.' },
    { symbol: 'DISCK', region: 'US', name: 'Discovery Inc. Class C' },
    { symbol: 'PENN', region: 'US', name: 'Penn National Gaming Inc.' },
    { symbol: 'IVZ', region: 'US', name: 'Invesco Ltd.' },
    { symbol: 'VNO', region: 'US', name: 'Vornado Realty Trust' },
    { symbol: 'NCLH', region: 'US', name: 'Norwegian Cruise Line Holdings Ltd.' },
    { symbol: 'ALK', region: 'US', name: 'Alaska Air Group Inc.' },
    { symbol: 'PVH', region: 'US', name: 'PVH Corp.' },
    { symbol: 'FOX', region: 'US', name: 'Fox Corporation Class B' },
    { symbol: 'RL', region: 'US', name: 'Ralph Lauren Corporation Class A' },
    { symbol: 'IPGP', region: 'US', name: 'IPG Photonics Corporation' },
    { symbol: 'DISCA', region: 'US', name: 'Discovery Inc. Class A' },
    { symbol: 'UAA', region: 'US', name: 'Under Armour Inc. Class A' },
    { symbol: 'UA', region: 'US', name: 'Under Armour Inc. Class C' },
    { symbol: 'NWS', region: 'US', name: 'News Corporation Class B' },
  ])
}

exports.down = () => {}
