exports.up = (knex) => {
  return knex('ticker').insert([
    { symbol: 'AAPL', region: 'US', name: 'Apple Inc' },
    { symbol: 'MSFT', region: 'US', name: 'Microsoft Corp' },
    { symbol: 'AMZN', region: 'US', name: 'Amazon.com Inc' },
    { symbol: 'GOOGL', region: 'US', name: 'Alphabet Inc Class A' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'FB', region: 'US', name: 'Meta Platforms Inc' },
    { symbol: 'NFLX', region: 'US', name: 'Netflix Inc' },
    { symbol: 'TSLA', region: 'US', name: 'Tesla Inc' },
    { symbol: 'WMT', region: 'US', name: 'Walmart Inc' },
    { symbol: 'AXP', region: 'US', name: 'American Express Co' },
    { symbol: 'AMGN', region: 'US', name: 'Amegen Inc' },
    { symbol: 'BA', region: 'US', name: 'Boeing Co' },
    { symbol: 'CAT', region: 'US', name: 'Caterpillar Inc' },
    { symbol: 'CSCO', region: 'US', name: 'Cisco Systems Inc' },
    { symbol: 'CVX', region: 'US', name: 'Chevron Corp' },
    { symbol: 'GS', region: 'US', name: 'Goldman Sachs Group Inc' },
    { symbol: 'HD', region: 'US', name: 'Home Depot Inc' },
    { symbol: 'HON', region: 'US', name: 'Honeywell International Inc' },
    { symbol: 'IBM', region: 'US', name: 'International Business Machines Corp' },
    { symbol: 'INTC', region: 'US', name: 'Intel Corp' },
    { symbol: 'JNJ', region: 'US', name: 'Johnson & Johnson' },
    { symbol: 'KO', region: 'US', name: 'Coca-Cola Co' },
    { symbol: 'JPM', region: 'US', name: 'JPMorgan Chase & Co' },
    { symbol: 'MCD', region: 'US', name: 'McDonald’s Corp' },
    { symbol: 'MMM', region: 'US', name: '3M Co' },
    { symbol: 'MRK', region: 'US', name: 'Merck & Co Inc' },
    { symbol: 'NKE', region: 'US', name: 'Nike Inc' },
    { symbol: 'PG', region: 'US', name: 'Procter & Gamble Co' },
    { symbol: 'TRV', region: 'US', name: 'Travelers Companies Inc' },
    { symbol: 'UNH', region: 'US', name: 'UnitedHealth Group Inc' },
    { symbol: 'CRM', region: 'US', name: 'Salesforce.Com Inc' },
    { symbol: 'VZ', region: 'US', name: 'Verizon Communications Inc' },
    { symbol: 'V', region: 'US', name: 'Visa Inc' },
    { symbol: 'WBA', region: 'US', name: 'Walgreens Boots Alliance Inc' },
    { symbol: 'DIS', region: 'US', name: 'Walt Disney Co' },
    { symbol: 'BB', region: 'US', name: 'BlackBerry Ltd' },
    { symbol: 'PYPL', region: 'US', name: 'Paypal Holdings Inc' },
    { symbol: 'XOM', region: 'US', name: 'Exxon Mobile Corporation' },
    { symbol: 'PFE', region: 'US', name: 'Pfizer Inc' },
    { symbol: 'ADBE', region: 'US', name: 'Adobe Inc' },
    { symbol: 'MA', region: 'US', name: 'Mastercard Incorporated Class A' },
    { symbol: 'COST', region: 'US', name: 'Costco Wholesale Corporation' },
    { symbol: 'PEP', region: 'US', name: 'PepsiCo Inc' },
    { symbol: 'WFC', region: 'US', name: 'Wells Fargo & Company' },
    { symbol: 'QCOM', region: 'US', name: 'Qualcomm Inc' },
    { symbol: 'T', region: 'US', name: 'AT&T Inc' },
    { symbol: 'AMD', region: 'US', name: 'Advanced Micro Devices Inc' },
    { symbol: 'LOW', region: 'US', name: 'Lowe’s Companies Inc' },
    { symbol: 'ORCL', region: 'US', name: 'Oracle Corporation' },
    { symbol: 'MS', region: 'US', name: 'Morgan Stanley' },
    { symbol: 'AMAT', region: 'US', name: 'Applied Materials Inc' },
    { symbol: 'TGT', region: 'US', name: 'Target Corporation' },
    { symbol: 'DE', region: 'US', name: 'Deere & Company' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
    { symbol: 'GOOG', region: 'US', name: 'Alphabet Inc Class C' },
  ])
}

exports.down = () => {}
