exports.up = (knex) => {
  return knex.schema
    .table('ticker_yearly', (table) => {
      table.string('peRatio', 5)
      table.string('pbRatio', 5)
      table.string('psRatio', 5)
      table.smallint('peYearlyIncrease')
      table.smallint('peYearlyDecrease')
      table.smallint('pbYearlyIncrease')
      table.smallint('pbYearlyDecrease')
      table.smallint('psYearlyIncrease')
      table.smallint('psYearlyDecrease')
      table.smallint('epsYearlyIncrease')
      table.smallint('epsYearlyDecrease')
      table.smallint('ebitdaYearlyIncrease')
      table.smallint('ebitdaYearlyDecrease')
      table.smallint('bookValueYearlyIncrease')
      table.smallint('bookValueYearlyDecrease')
      table.smallint('equityYearlyIncrease')
      table.smallint('equityYearlyDecrease')
      table.smallint('freeCashFlowYearlyIncrease')
      table.smallint('freeCashFlowYearlyDecrease')
    })
    .table('ticker_quarterly', (table) => {
      table.string('peRatio', 5)
      table.string('pbRatio', 5)
      table.string('psRatio', 5)
      table.smallint('peQuarterlyIncrease')
      table.smallint('peQuarterlyDecrease')
      table.smallint('pbQuarterlyIncrease')
      table.smallint('pbQuarterlyDecrease')
      table.smallint('psQuarterlyIncrease')
      table.smallint('psQuarterlyDecrease')
      table.smallint('grossMarginQuarterlyIncrease')
      table.smallint('grossMarginQuarterlyDecrease')
      table.string('grossMarginChangePercent', 5)
      table.smallint('debtEquityQuarterlyIncrease')
      table.smallint('debtEquityQuarterlyDecrease')
      table.smallint('epsQuarterlyIncrease')
      table.smallint('epsQuarterlyDecrease')
      table.smallint('ebitdaQuarterlyIncrease')
      table.smallint('ebitdaQuarterlyDecrease')
      table.smallint('bookValueQuarterlyIncrease')
      table.smallint('bookValueQuarterlyDecrease')
      table.smallint('equityQuarterlyIncrease')
      table.smallint('equityQuarterlyDecrease')
      table.smallint('freeCashFlowQuarterlyIncrease')
      table.smallint('freeCashFlowQuarterlyDecrease')
      table.smallint('roaQuarterlyIncrease')
      table.smallint('roaQuarterlyDecrease')
      table.smallint('roeQuarterlyIncrease')
      table.smallint('roeQuarterlyDecrease')
    })
}

exports.down = (knex) => {
  return knex.schema
    .table('ticker_yearly', (table) => {
      table.dropColumn('peRatio')
      table.dropColumn('pbRatio')
      table.dropColumn('psRatio')
      table.dropColumn('peYearlyIncrease')
      table.dropColumn('peYearlyDecrease')
      table.dropColumn('pbYearlyIncrease')
      table.dropColumn('pbYearlyDecrease')
      table.dropColumn('psYearlyIncrease')
      table.dropColumn('psYearlyDecrease')
      table.dropColumn('epsYearlyIncrease')
      table.dropColumn('epsYearlyDecrease')
      table.dropColumn('ebitdaYearlyIncrease')
      table.dropColumn('ebitdaYearlyDecrease')
      table.dropColumn('bookValueYearlyIncrease')
      table.dropColumn('bookValueYearlyDecrease')
      table.dropColumn('equityYearlyIncrease')
      table.dropColumn('equityYearlyDecrease')
      table.dropColumn('freeCashFlowYearlyIncrease')
      table.dropColumn('freeCashFlowYearlyDecrease')
    })
    .table('ticker_quarterly', (table) => {
      table.dropColumn('peRatio')
      table.dropColumn('pbRatio')
      table.dropColumn('psRatio')
      table.dropColumn('peQuarterlyIncrease')
      table.dropColumn('peQuarterlyDecrease')
      table.dropColumn('pbQuarterlyIncrease')
      table.dropColumn('pbQuarterlyDecrease')
      table.dropColumn('psQuarterlyIncrease')
      table.dropColumn('psQuarterlyDecrease')
      table.dropColumn('grossMarginQuarterlyIncrease')
      table.dropColumn('grossMarginQuarterlyDecrease')
      table.dropColumn('grossMarginChangePercent')
      table.dropColumn('debtEquityQuarterlyIncrease')
      table.dropColumn('debtEquityQuarterlyDecrease')
      table.dropColumn('epsQuarterlyIncrease')
      table.dropColumn('epsQuarterlyDecrease')
      table.dropColumn('ebitdaQuarterlyIncrease')
      table.dropColumn('ebitdaQuarterlyDecrease')
      table.dropColumn('bookValueQuarterlyIncrease')
      table.dropColumn('bookValueQuarterlyDecrease')
      table.dropColumn('equityQuarterlyIncrease')
      table.dropColumn('equityQuarterlyDecrease')
      table.dropColumn('freeCashFlowQuarterlyIncrease')
      table.dropColumn('freeCashFlowQuarterlyDecrease')
      table.dropColumn('roaQuarterlyIncrease')
      table.dropColumn('roaQuarterlyDecrease')
      table.dropColumn('roeQuarterlyIncrease')
      table.dropColumn('roeQuarterlyDecrease')
    })
}
