exports.up = (knex) => {
  return knex.schema
    .createTable('ticker_quarterly', (table) => {
      table.increments('id')
      table.integer('tickerId').notNullable()
      table.specificType('quarter', 'CHAR(7)').notNullable()
      table.specificType('earningDate', 'CHAR(10)')
      table.string('equity', 20)
      table.string('totalAssets', 20)
      table.string('totalLiabilities', 20)
      table.string('freeCashFlow', 20)
      table.string('grossMargin', 20)
      table.string('debtEquity', 20)
      table.string('outstandingShares', 20)
      table.string('roa', 20)
      table.string('roe', 20)
      table.string('eps', 10)
      table.string('ebitda', 20)
      table.string('netIncome', 20)
      table.string('grossProfit', 20)
      table.string('totalRevenue', 20)
      table.string('costOfRevenue', 20)
      table.string('epsQoQ', 5)
      table.string('revenueQoQ', 5)
      table.smallint('profitQuarterlyIncrease')
      table.smallint('profitQuarterlyDecrease')
      table.smallint('revenueQuarterlyIncrease')
      table.smallint('revenueQuarterlyDecrease')
      table.smallint('incomeQuarterlyIncrease')
      table.smallint('incomeQuarterlyDecrease')
      table.string('grossMarginQoQ', 7)
      table.string('debtEquityQoQ', 7)
      table.string('bookValue', 20)
      table.string('peRatio', 7)
      table.string('pbRatio', 7)
      table.string('psRatio', 7)
      table.smallint('peQuarterlyIncrease')
      table.smallint('peQuarterlyDecrease')
      table.smallint('pbQuarterlyIncrease')
      table.smallint('pbQuarterlyDecrease')
      table.smallint('psQuarterlyIncrease')
      table.smallint('psQuarterlyDecrease')
      table.smallint('grossMarginQuarterlyIncrease')
      table.smallint('grossMarginQuarterlyDecrease')
      table.smallint('debtEquityQuarterlyIncrease')
      table.smallint('debtEquityQuarterlyDecrease')
      table.smallint('epsQuarterlyIncrease')
      table.smallint('epsQuarterlyDecrease')
      table.smallint('ebitdaQuarterlyIncrease')
      table.smallint('ebitdaQuarterlyDecrease')
      table.smallint('bookValueQuarterlyIncrease')
      table.smallint('bookValueQuarterlyDecrease')
      table.smallint('equityQuarterlyIncrease')
      table.smallint('equityQuarterlyDecrease')
      table.smallint('freeCashFlowQuarterlyIncrease')
      table.smallint('freeCashFlowQuarterlyDecrease')
      table.smallint('roaQuarterlyIncrease')
      table.smallint('roaQuarterlyDecrease')
      table.smallint('roeQuarterlyIncrease')
      table.smallint('roeQuarterlyDecrease')
      table.unique(['tickerId', 'quarter'], 'ticker_quarterly_ukey')
      table.foreign('tickerId').references('id').inTable('ticker')
    })
}

exports.down = (knex) => {
  return knex.schema.dropTable('ticker_quarterly')
}
