import { Day } from './trader'

export const Preference = Object.freeze({
  HigherPrice: 1,
  LowerPrice: 2,
  HigherQuarterEPS: 3,
  LowerQuarterEPS: 4,
  HigherQuarterEBITDA: 5,
  LowerQuarterEBITDA: 6,
  HigherQuarterIncome: 7,
  LowerQuarterIncome: 8,
  HigherQuarterProfit: 9,
  LowerQuarterProfit: 10,
  HigherQuarterRevenue: 11,
  LowerQuarterRevenue: 12,
  HigherYearEPS: 13,
  LowerYearEPS: 14,
  HigherYearEBITDA: 15,
  LowerYearEBITDA: 16,
  HigherYearIncome: 17,
  LowerYearIncome: 18,
  HigherYearProfit: 19,
  LowerYearProfit: 20,
  HigherYearRevenue: 21,
  LowerYearRevenue: 22,
})

const ContinuousMovement = [1, 2, 3, 5]
const PercentChange = [-5, -3, -2, -1, 1, 2, 3, 5]

export const Options = {
  priceDailyIncreaseBuy: [...ContinuousMovement],
  priceDailyIncreaseSell: [...ContinuousMovement],
  priceDailyDecreaseBuy: [...ContinuousMovement],
  priceDailyDecreaseSell: [...ContinuousMovement],
  priceWeeklyIncreaseBuy: [...ContinuousMovement],
  priceWeeklyIncreaseSell: [...ContinuousMovement],
  priceWeeklyDecreaseBuy: [...ContinuousMovement],
  priceWeeklyDecreaseSell: [...ContinuousMovement],
  priceMonthlyIncreaseBuy: [...ContinuousMovement],
  priceMonthlyIncreaseSell: [...ContinuousMovement],
  priceMonthlyDecreaseBuy: [...ContinuousMovement],
  priceMonthlyDecreaseSell: [...ContinuousMovement],
  priceQuarterlyIncreaseBuy: [...ContinuousMovement],
  priceQuarterlyIncreaseSell: [...ContinuousMovement],
  priceQuarterlyDecreaseBuy: [...ContinuousMovement],
  priceQuarterlyDecreaseSell: [...ContinuousMovement],
  priceYearlyIncreaseBuy: [...ContinuousMovement],
  priceYearlyIncreaseSell: [...ContinuousMovement],
  priceYearlyDecreaseBuy: [...ContinuousMovement],
  priceYearlyDecreaseSell: [...ContinuousMovement],
  epsQuarterlyBeatBuy: [...ContinuousMovement],
  epsQuarterlyMissBuy: [...ContinuousMovement],
  epsQuarterlyBeatSell: [...ContinuousMovement],
  epsQuarterlyMissSell: [...ContinuousMovement],
  profitQuarterlyIncreaseBuy: [...ContinuousMovement],
  profitQuarterlyIncreaseSell: [...ContinuousMovement],
  profitQuarterlyDecreaseBuy: [...ContinuousMovement],
  profitQuarterlyDecreaseSell: [...ContinuousMovement],
  incomeQuarterlyIncreaseBuy: [...ContinuousMovement],
  incomeQuarterlyIncreaseSell: [...ContinuousMovement],
  incomeQuarterlyDecreaseBuy: [...ContinuousMovement],
  incomeQuarterlyDecreaseSell: [...ContinuousMovement],
  revenueQuarterlyIncreaseBuy: [...ContinuousMovement],
  revenueQuarterlyIncreaseSell: [...ContinuousMovement],
  revenueQuarterlyDecreaseBuy: [...ContinuousMovement],
  revenueQuarterlyDecreaseSell: [...ContinuousMovement],
  profitYearlyIncreaseBuy: [...ContinuousMovement],
  profitYearlyIncreaseSell: [...ContinuousMovement],
  profitYearlyDecreaseBuy: [...ContinuousMovement],
  profitYearlyDecreaseSell: [...ContinuousMovement],
  incomeYearlyIncreaseBuy: [...ContinuousMovement],
  incomeYearlyIncreaseSell: [...ContinuousMovement],
  incomeYearlyDecreaseBuy: [...ContinuousMovement],
  incomeYearlyDecreaseSell: [...ContinuousMovement],
  revenueYearlyIncreaseBuy: [...ContinuousMovement],
  revenueYearlyIncreaseSell: [...ContinuousMovement],
  revenueYearlyDecreaseBuy: [...ContinuousMovement],
  revenueYearlyDecreaseSell: [...ContinuousMovement],
  inflationYearlyIncreaseBuy: [...ContinuousMovement],
  inflationYearlyDecreaseBuy: [...ContinuousMovement],
  inflationYearlyIncreaseSell: [...ContinuousMovement],
  inflationYearlyDecreaseSell: [...ContinuousMovement],
  fundsRateMonthlyIncreaseBuy: [...ContinuousMovement],
  fundsRateMonthlyDecreaseBuy: [...ContinuousMovement],
  fundsRateMonthlyIncreaseSell: [...ContinuousMovement],
  fundsRateMonthlyDecreaseSell: [...ContinuousMovement],
  thirtyYearsTreasuryMonthlyIncreaseBuy: [...ContinuousMovement],
  thirtyYearsTreasuryMonthlyDecreaseBuy: [...ContinuousMovement],
  thirtyYearsTreasuryMonthlyIncreaseSell: [...ContinuousMovement],
  thirtyYearsTreasuryMonthlyDecreaseSell: [...ContinuousMovement],
  tenYearsTreasuryMonthlyIncreaseBuy: [...ContinuousMovement],
  tenYearsTreasuryMonthlyDecreaseBuy: [...ContinuousMovement],
  tenYearsTreasuryMonthlyIncreaseSell: [...ContinuousMovement],
  tenYearsTreasuryMonthlyDecreaseSell: [...ContinuousMovement],
  inflationMonthlyIncreaseBuy: [...ContinuousMovement],
  inflationMonthlyDecreaseBuy: [...ContinuousMovement],
  inflationMonthlyIncreaseSell: [...ContinuousMovement],
  inflationMonthlyDecreaseSell: [...ContinuousMovement],
  cpiMonthlyIncreaseBuy: [...ContinuousMovement],
  cpiMonthlyDecreaseBuy: [...ContinuousMovement],
  cpiMonthlyIncreaseSell: [...ContinuousMovement],
  cpiMonthlyDecreaseSell: [...ContinuousMovement],
  consumerSentimentMonthlyIncreaseBuy: [...ContinuousMovement],
  consumerSentimentMonthlyDecreaseBuy: [...ContinuousMovement],
  consumerSentimentMonthlyIncreaseSell: [...ContinuousMovement],
  consumerSentimentMonthlyDecreaseSell: [...ContinuousMovement],
  retailSalesMonthlyIncreaseBuy: [...ContinuousMovement],
  retailSalesMonthlyDecreaseBuy: [...ContinuousMovement],
  retailSalesMonthlyIncreaseSell: [...ContinuousMovement],
  retailSalesMonthlyDecreaseSell: [...ContinuousMovement],
  durableGoodsMonthlyIncreaseBuy: [...ContinuousMovement],
  durableGoodsMonthlyDecreaseBuy: [...ContinuousMovement],
  durableGoodsMonthlyIncreaseSell: [...ContinuousMovement],
  durableGoodsMonthlyDecreaseSell: [...ContinuousMovement],
  unemploymentRateMonthlyIncreaseBuy: [...ContinuousMovement],
  unemploymentRateMonthlyDecreaseBuy: [...ContinuousMovement],
  unemploymentRateMonthlyIncreaseSell: [...ContinuousMovement],
  unemploymentRateMonthlyDecreaseSell: [...ContinuousMovement],
  nonfarmPayrollMonthlyIncreaseBuy: [...ContinuousMovement],
  nonfarmPayrollMonthlyDecreaseBuy: [...ContinuousMovement],
  nonfarmPayrollMonthlyIncreaseSell: [...ContinuousMovement],
  nonfarmPayrollMonthlyDecreaseSell: [...ContinuousMovement],
  gdpYearlyChangeAboveBuy: [...PercentChange],
  gdpYearlyChangeAboveSell: [...PercentChange],
  gdpYearlyChangeBelowBuy: [...PercentChange],
  gdpYearlyChangeBelowSell: [...PercentChange],
  gdpQuarterlyChangeAboveBuy: [...PercentChange],
  gdpQuarterlyChangeAboveSell: [...PercentChange],
  gdpQuarterlyChangeBelowBuy: [...PercentChange],
  gdpQuarterlyChangeBelowSell: [...PercentChange],
  gdpQuarterlyYoYChangeAboveBuy: [...PercentChange],
  gdpQuarterlyYoYChangeAboveSell: [...PercentChange],
  gdpQuarterlyYoYChangeBelowBuy: [...PercentChange],
  gdpQuarterlyYoYChangeBelowSell: [...PercentChange],
  cashMaxPercent: [0, 10, 20, 30, 50, 80, 100],
  tickerMinPercent: [1, 2, 3, 5, 8, 13, 21, 34, 55],
  tickerMaxPercent: [1, 2, 3, 5, 8, 13, 21, 34, 55],
  holdingBuyPercent: [1, 2, 3, 5, 8, 13, 21, 34, 55],
  holdingSellPercent: [20, 40, 60, 80, 100],
  tradeFrequency: [
    1, 2, 3, Day.Week,
    Day.HalfMonth, Day.Month,
    Day.HalfQuarter, Day.Quarter,
    Day.HalfYear, Day.Year,
  ],
  rebalanceFrequency: [
    0, Day.Week,
    Day.HalfMonth, Day.Month,
    Day.HalfQuarter, Day.Quarter,
    Day.HalfYear, Day.Year,
  ],
  buyPreference: Object.values(Preference),
  sellPreference: Object.values(Preference),
}
