export const Preference = Object.freeze({
  HigherPrice: 1,
  LowerPrice: 2,
  HigherQuarterEPS: 3,
  LowerQuarterEPS: 4,
  HigherQuarterEBITDA: 5,
  LowerQuarterEBITDA: 6,
  HigherQuarterIncome: 7,
  LowerQuarterIncome: 8,
  HigherQuarterProfit: 9,
  LowerQuarterProfit: 10,
  HigherQuarterRevenue: 11,
  LowerQuarterRevenue: 12,
  HigherYearEPS: 13,
  LowerYearEPS: 14,
  HigherYearEBITDA: 15,
  LowerYearEBITDA: 16,
  HigherYearIncome: 17,
  LowerYearIncome: 18,
  HigherYearProfit: 19,
  LowerYearProfit: 20,
  HigherYearRevenue: 21,
  LowerYearRevenue: 22,
})

const ContinuousMovement = [1, 2, 3, 5]

const earningPercent = [1, 3, 5, 7, 10, 30, 50, 70]
const debtEquityPercent = [0.5, 1, 1.5, 2, 2.5, 3]
const fundsRatePercent = [0.5, 1, 2, 3, 4, 5]

const PercentChange = [-5, -3, -2, -1, 1, 2, 3, 5]
const HoldingPercent = [1, 2, 3, 5, 8, 13, 21, 34]

export const Options = {
  priceDailyIncreaseBuy: [...ContinuousMovement],
  priceDailyIncreaseSell: [...ContinuousMovement],
  priceDailyDecreaseBuy: [...ContinuousMovement],
  priceDailyDecreaseSell: [...ContinuousMovement],
  priceWeeklyIncreaseBuy: [...ContinuousMovement],
  priceWeeklyIncreaseSell: [...ContinuousMovement],
  priceWeeklyDecreaseBuy: [...ContinuousMovement],
  priceWeeklyDecreaseSell: [...ContinuousMovement],
  priceMonthlyIncreaseBuy: [...ContinuousMovement],
  priceMonthlyIncreaseSell: [...ContinuousMovement],
  priceMonthlyDecreaseBuy: [...ContinuousMovement],
  priceMonthlyDecreaseSell: [...ContinuousMovement],
  priceQuarterlyIncreaseBuy: [...ContinuousMovement],
  priceQuarterlyIncreaseSell: [...ContinuousMovement],
  priceQuarterlyDecreaseBuy: [...ContinuousMovement],
  priceQuarterlyDecreaseSell: [...ContinuousMovement],
  priceYearlyIncreaseBuy: [...ContinuousMovement],
  priceYearlyIncreaseSell: [...ContinuousMovement],
  priceYearlyDecreaseBuy: [...ContinuousMovement],
  priceYearlyDecreaseSell: [...ContinuousMovement],
  profitQuarterlyIncreaseBuy: [...ContinuousMovement],
  profitQuarterlyIncreaseSell: [...ContinuousMovement],
  profitQuarterlyDecreaseBuy: [...ContinuousMovement],
  profitQuarterlyDecreaseSell: [...ContinuousMovement],
  incomeQuarterlyIncreaseBuy: [...ContinuousMovement],
  incomeQuarterlyIncreaseSell: [...ContinuousMovement],
  incomeQuarterlyDecreaseBuy: [...ContinuousMovement],
  incomeQuarterlyDecreaseSell: [...ContinuousMovement],
  revenueQuarterlyIncreaseBuy: [...ContinuousMovement],
  revenueQuarterlyIncreaseSell: [...ContinuousMovement],
  revenueQuarterlyDecreaseBuy: [...ContinuousMovement],
  revenueQuarterlyDecreaseSell: [...ContinuousMovement],
  profitYearlyIncreaseBuy: [...ContinuousMovement],
  profitYearlyIncreaseSell: [...ContinuousMovement],
  profitYearlyDecreaseBuy: [...ContinuousMovement],
  profitYearlyDecreaseSell: [...ContinuousMovement],
  incomeYearlyIncreaseBuy: [...ContinuousMovement],
  incomeYearlyIncreaseSell: [...ContinuousMovement],
  incomeYearlyDecreaseBuy: [...ContinuousMovement],
  incomeYearlyDecreaseSell: [...ContinuousMovement],
  revenueYearlyIncreaseBuy: [...ContinuousMovement],
  revenueYearlyIncreaseSell: [...ContinuousMovement],
  revenueYearlyDecreaseBuy: [...ContinuousMovement],
  revenueYearlyDecreaseSell: [...ContinuousMovement],
  inflationYearlyIncreaseBuy: [...ContinuousMovement],
  inflationYearlyDecreaseBuy: [...ContinuousMovement],
  inflationYearlyIncreaseSell: [...ContinuousMovement],
  inflationYearlyDecreaseSell: [...ContinuousMovement],
  fundsRateMonthlyIncreaseBuy: [...ContinuousMovement],
  fundsRateMonthlyDecreaseBuy: [...ContinuousMovement],
  fundsRateMonthlyIncreaseSell: [...ContinuousMovement],
  fundsRateMonthlyDecreaseSell: [...ContinuousMovement],
  thirtyYearsTreasuryMonthlyIncreaseBuy: [...ContinuousMovement],
  thirtyYearsTreasuryMonthlyDecreaseBuy: [...ContinuousMovement],
  thirtyYearsTreasuryMonthlyIncreaseSell: [...ContinuousMovement],
  thirtyYearsTreasuryMonthlyDecreaseSell: [...ContinuousMovement],
  tenYearsTreasuryMonthlyIncreaseBuy: [...ContinuousMovement],
  tenYearsTreasuryMonthlyDecreaseBuy: [...ContinuousMovement],
  tenYearsTreasuryMonthlyIncreaseSell: [...ContinuousMovement],
  tenYearsTreasuryMonthlyDecreaseSell: [...ContinuousMovement],
  inflationMonthlyIncreaseBuy: [...ContinuousMovement],
  inflationMonthlyDecreaseBuy: [...ContinuousMovement],
  inflationMonthlyIncreaseSell: [...ContinuousMovement],
  inflationMonthlyDecreaseSell: [...ContinuousMovement],
  cpiMonthlyIncreaseBuy: [...ContinuousMovement],
  cpiMonthlyDecreaseBuy: [...ContinuousMovement],
  cpiMonthlyIncreaseSell: [...ContinuousMovement],
  cpiMonthlyDecreaseSell: [...ContinuousMovement],
  consumerSentimentMonthlyIncreaseBuy: [...ContinuousMovement],
  consumerSentimentMonthlyDecreaseBuy: [...ContinuousMovement],
  consumerSentimentMonthlyIncreaseSell: [...ContinuousMovement],
  consumerSentimentMonthlyDecreaseSell: [...ContinuousMovement],
  unemploymentRateMonthlyIncreaseBuy: [...ContinuousMovement],
  unemploymentRateMonthlyDecreaseBuy: [...ContinuousMovement],
  unemploymentRateMonthlyIncreaseSell: [...ContinuousMovement],
  unemploymentRateMonthlyDecreaseSell: [...ContinuousMovement],
  nonfarmPayrollMonthlyIncreaseBuy: [...ContinuousMovement],
  nonfarmPayrollMonthlyDecreaseBuy: [...ContinuousMovement],
  nonfarmPayrollMonthlyIncreaseSell: [...ContinuousMovement],
  nonfarmPayrollMonthlyDecreaseSell: [...ContinuousMovement],
  gdpYearlyChangeAboveBuy: [...PercentChange],
  gdpYearlyChangeAboveSell: [...PercentChange],
  gdpYearlyChangeBelowBuy: [...PercentChange],
  gdpYearlyChangeBelowSell: [...PercentChange],
  seasonalGDPQoQAboveBuy: [...PercentChange],
  seasonalGDPQoQAboveSell: [...PercentChange],
  seasonalGDPQoQBelowBuy: [...PercentChange],
  seasonalGDPQoQBelowSell: [...PercentChange],
  seasonalGDPYoYAboveBuy: [...PercentChange],
  seasonalGDPYoYAboveSell: [...PercentChange],
  seasonalGDPYoYBelowBuy: [...PercentChange],
  seasonalGDPYoYBelowSell: [...PercentChange],
  peQuarterlyIncreaseBuy: [...ContinuousMovement],
  peQuarterlyIncreaseSell: [...ContinuousMovement],
  peQuarterlyDecreaseBuy: [...ContinuousMovement],
  peQuarterlyDecreaseSell: [...ContinuousMovement],
  pbQuarterlyIncreaseBuy: [...ContinuousMovement],
  pbQuarterlyIncreaseSell: [...ContinuousMovement],
  pbQuarterlyDecreaseBuy: [...ContinuousMovement],
  pbQuarterlyDecreaseSell: [...ContinuousMovement],
  psQuarterlyIncreaseBuy: [...ContinuousMovement],
  psQuarterlyIncreaseSell: [...ContinuousMovement],
  psQuarterlyDecreaseBuy: [...ContinuousMovement],
  psQuarterlyDecreaseSell: [...ContinuousMovement],
  epsQuarterlyIncreaseBuy: [...ContinuousMovement],
  epsQuarterlyIncreaseSell: [...ContinuousMovement],
  epsQuarterlyDecreaseBuy: [...ContinuousMovement],
  epsQuarterlyDecreaseSell: [...ContinuousMovement],
  ebitdaQuarterlyIncreaseBuy: [...ContinuousMovement],
  ebitdaQuarterlyIncreaseSell: [...ContinuousMovement],
  ebitdaQuarterlyDecreaseBuy: [...ContinuousMovement],
  ebitdaQuarterlyDecreaseSell: [...ContinuousMovement],
  freeCashFlowQuarterlyIncreaseBuy: [...ContinuousMovement],
  freeCashFlowQuarterlyIncreaseSell: [...ContinuousMovement],
  freeCashFlowQuarterlyDecreaseBuy: [...ContinuousMovement],
  freeCashFlowQuarterlyDecreaseSell: [...ContinuousMovement],
  roaQuarterlyIncreaseBuy: [...ContinuousMovement],
  roaQuarterlyIncreaseSell: [...ContinuousMovement],
  roaQuarterlyDecreaseBuy: [...ContinuousMovement],
  roaQuarterlyDecreaseSell: [...ContinuousMovement],
  roeQuarterlyIncreaseBuy: [...ContinuousMovement],
  roeQuarterlyIncreaseSell: [...ContinuousMovement],
  roeQuarterlyDecreaseBuy: [...ContinuousMovement],
  roeQuarterlyDecreaseSell: [...ContinuousMovement],
  grossMarginQuarterlyIncreaseBuy: [...ContinuousMovement],
  grossMarginQuarterlyIncreaseSell: [...ContinuousMovement],
  grossMarginQuarterlyDecreaseBuy: [...ContinuousMovement],
  grossMarginQuarterlyDecreaseSell: [...ContinuousMovement],
  debtEquityQuarterlyIncreaseBuy: [...ContinuousMovement],
  debtEquityQuarterlyIncreaseSell: [...ContinuousMovement],
  debtEquityQuarterlyDecreaseBuy: [...ContinuousMovement],
  debtEquityQuarterlyDecreaseSell: [...ContinuousMovement],
  peRatioQuarterlyAboveBuy: [...earningPercent],
  peRatioQuarterlyAboveSell: [...earningPercent],
  peRatioQuarterlyBelowBuy: [...earningPercent],
  peRatioQuarterlyBelowSell: [...earningPercent],
  pbRatioQuarterlyAboveBuy: [...earningPercent],
  pbRatioQuarterlyAboveSell: [...earningPercent],
  pbRatioQuarterlyBelowBuy: [...earningPercent],
  pbRatioQuarterlyBelowSell: [...earningPercent],
  psRatioQuarterlyAboveBuy: [...earningPercent],
  psRatioQuarterlyAboveSell: [...earningPercent],
  psRatioQuarterlyBelowBuy: [...earningPercent],
  psRatioQuarterlyBelowSell: [...earningPercent],
  roaQuarterlyAboveBuy: [...earningPercent],
  roaQuarterlyAboveSell: [...earningPercent],
  roaQuarterlyBelowBuy: [...earningPercent],
  roaQuarterlyBelowSell: [...earningPercent],
  roeQuarterlyAboveBuy: [...earningPercent],
  roeQuarterlyAboveSell: [...earningPercent],
  roeQuarterlyBelowBuy: [...earningPercent],
  roeQuarterlyBelowSell: [...earningPercent],
  grossMarginQuarterlyAboveBuy: [...earningPercent],
  grossMarginQuarterlyAboveSell: [...earningPercent],
  grossMarginQuarterlyBelowBuy: [...earningPercent],
  grossMarginQuarterlyBelowSell: [...earningPercent],
  debtEquityQuarterlyAboveBuy: [...debtEquityPercent],
  debtEquityQuarterlyAboveSell: [...debtEquityPercent],
  debtEquityQuarterlyBelowBuy: [...debtEquityPercent],
  debtEquityQuarterlyBelowSell: [...debtEquityPercent],
  peYearlyIncreaseBuy: [...ContinuousMovement],
  peYearlyIncreaseSell: [...ContinuousMovement],
  peYearlyDecreaseBuy: [...ContinuousMovement],
  peYearlyDecreaseSell: [...ContinuousMovement],
  pbYearlyIncreaseBuy: [...ContinuousMovement],
  pbYearlyIncreaseSell: [...ContinuousMovement],
  pbYearlyDecreaseBuy: [...ContinuousMovement],
  pbYearlyDecreaseSell: [...ContinuousMovement],
  psYearlyIncreaseBuy: [...ContinuousMovement],
  psYearlyIncreaseSell: [...ContinuousMovement],
  psYearlyDecreaseBuy: [...ContinuousMovement],
  psYearlyDecreaseSell: [...ContinuousMovement],
  epsYearlyIncreaseBuy: [...ContinuousMovement],
  epsYearlyIncreaseSell: [...ContinuousMovement],
  epsYearlyDecreaseBuy: [...ContinuousMovement],
  epsYearlyDecreaseSell: [...ContinuousMovement],
  ebitdaYearlyIncreaseBuy: [...ContinuousMovement],
  ebitdaYearlyIncreaseSell: [...ContinuousMovement],
  ebitdaYearlyDecreaseBuy: [...ContinuousMovement],
  ebitdaYearlyDecreaseSell: [...ContinuousMovement],
  freeCashFlowYearlyIncreaseBuy: [...ContinuousMovement],
  freeCashFlowYearlyIncreaseSell: [...ContinuousMovement],
  freeCashFlowYearlyDecreaseBuy: [...ContinuousMovement],
  freeCashFlowYearlyDecreaseSell: [...ContinuousMovement],
  peRatioYearlyAboveBuy: [...earningPercent],
  peRatioYearlyAboveSell: [...earningPercent],
  peRatioYearlyBelowBuy: [...earningPercent],
  peRatioYearlyBelowSell: [...earningPercent],
  pbRatioYearlyAboveBuy: [...earningPercent],
  pbRatioYearlyAboveSell: [...earningPercent],
  pbRatioYearlyBelowBuy: [...earningPercent],
  pbRatioYearlyBelowSell: [...earningPercent],
  psRatioYearlyAboveBuy: [...earningPercent],
  psRatioYearlyAboveSell: [...earningPercent],
  psRatioYearlyBelowBuy: [...earningPercent],
  psRatioYearlyBelowSell: [...earningPercent],
  fundsRateMonthlyAboveBuy: [...fundsRatePercent],
  fundsRateMonthlyAboveSell: [...fundsRatePercent],
  fundsRateMonthlyBelowBuy: [...fundsRatePercent],
  fundsRateMonthlyBelowSell: [...fundsRatePercent],
  tenYearsTreasuryMonthlyAboveBuy: number | null;
  tenYearsTreasuryMonthlyAboveSell: number | null;
  tenYearsTreasuryMonthlyBelowBuy: number | null;
  tenYearsTreasuryMonthlyBelowSell: number | null;
  thirtyYearsTreasuryMonthlyAboveBuy: number | null;
  thirtyYearsTreasuryMonthlyAboveSell: number | null;
  thirtyYearsTreasuryMonthlyBelowBuy: number | null;
  thirtyYearsTreasuryMonthlyBelowSell: number | null;
  inflationMonthlyAboveBuy: number | null;
  inflationMonthlyAboveSell: number | null;
  inflationMonthlyBelowBuy: number | null;
  inflationMonthlyBelowSell: number | null;
  consumerSentimentMonthlyAboveBuy: number | null;
  consumerSentimentMonthlyAboveSell: number | null;
  consumerSentimentMonthlyBelowBuy: number | null;
  consumerSentimentMonthlyBelowSell: number | null;
  nonfarmPayrollMonthlyAboveBuy: number | null;
  nonfarmPayrollMonthlyAboveSell: number | null;
  nonfarmPayrollMonthlyBelowBuy: number | null;
  nonfarmPayrollMonthlyBelowSell: number | null;
  seasonalGDPQuarterlyIncreaseBuy: [...ContinuousMovement],
  seasonalGDPQuarterlyIncreaseSell: [...ContinuousMovement],
  seasonalGDPQuarterlyDecreaseBuy: [...ContinuousMovement],
  seasonalGDPQuarterlyDecreaseSell: [...ContinuousMovement],
  gdpYearlyIncreaseBuy: [...ContinuousMovement],
  gdpYearlyIncreaseSell: [...ContinuousMovement],
  gdpYearlyDecreaseBuy: [...ContinuousMovement],
  gdpYearlyDecreaseSell: [...ContinuousMovement],
  inflationYearlyAboveBuy: number | null;
  inflationYearlyAboveSell: number | null;
  inflationYearlyBelowBuy: number | null;
  inflationYearlyBelowSell: number | null;
  cashMaxPercent: [0, 10, 20, 30, 50, 80, 100],
  tickerMinPercent: [...HoldingPercent],
  tickerMaxPercent: [...HoldingPercent],
  holdingBuyPercent: [...HoldingPercent],
  holdingSellPercent: [20, 40, 60, 80, 100],
  tradeFrequency: [
    2, 5, 15, 30, 90, 180, 360,
  ],
  rebalanceFrequency: [
    0, 5, 15, 30, 90, 180, 360,
  ],
  buyPreference: Object.values(Preference),
  sellPreference: Object.values(Preference),
}
