import { day } from './time'

export const preference = {
  HIGHER_PRICE: 1,
  LOWER_PRICE: 2,
  HIGHER_QUARTER_EPS: 3,
  LOWER_QUARTER_EPS: 4,
  HIGHER_QUARTER_EBITDA: 5,
  LOWER_QUARTER_EBITDA: 6,
  HIGHER_QUARTER_INCOME: 7,
  LOWER_QUARTER_INCOME: 8,
  HIGHER_QUARTER_PROFIT: 9,
  LOWER_QUARTER_PROFIT: 10,
  HIGHER_QUARTER_REVENUE: 11,
  LOWER_QUARTER_REVENUE: 12,
  HIGHER_YEAR_EPS: 13,
  LOWER_YEAR_EPS: 14,
  HIGHER_YEAR_EBITDA: 15,
  LOWER_YEAR_EBITDA: 16,
  HIGHER_YEAR_INCOME: 17,
  LOWER_YEAR_INCOME: 18,
  HIGHER_YEAR_PROFIT: 19,
  LOWER_YEAR_PROFIT: 20,
  HIGHER_YEAR_REVENUE: 21,
  LOWER_YEAR_REVENUE: 22,
}

const CONTINUOUS_MOVEMENT = [1, 2, 3, 5]
const PERCENT_CHANGE = [-5, -3, -2, -1, 1, 2, 3, 5]

export const options = {
  priceDailyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceDailyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  priceDailyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceDailyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  priceWeeklyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceWeeklyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  priceWeeklyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceWeeklyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  priceMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  priceMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  priceQuarterlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceQuarterlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  priceQuarterlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceQuarterlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  priceYearlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceYearlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  priceYearlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  priceYearlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  epsQuarterlyBeatBuy: [...CONTINUOUS_MOVEMENT],
  epsQuarterlyMissBuy: [...CONTINUOUS_MOVEMENT],
  epsQuarterlyBeatSell: [...CONTINUOUS_MOVEMENT],
  epsQuarterlyMissSell: [...CONTINUOUS_MOVEMENT],
  profitQuarterlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  profitQuarterlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  profitQuarterlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  profitQuarterlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  incomeQuarterlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  incomeQuarterlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  incomeQuarterlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  incomeQuarterlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  revenueQuarterlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  revenueQuarterlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  revenueQuarterlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  revenueQuarterlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  profitYearlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  profitYearlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  profitYearlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  profitYearlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  incomeYearlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  incomeYearlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  incomeYearlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  incomeYearlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  revenueYearlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  revenueYearlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  revenueYearlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  revenueYearlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  inflationYearlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  inflationYearlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  inflationYearlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  inflationYearlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  fundsRateMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  fundsRateMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  fundsRateMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  fundsRateMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  thirtyYearsTreasuryMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  thirtyYearsTreasuryMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  thirtyYearsTreasuryMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  thirtyYearsTreasuryMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  tenYearsTreasuryMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  tenYearsTreasuryMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  tenYearsTreasuryMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  tenYearsTreasuryMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  inflationMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  inflationMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  inflationMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  inflationMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  cpiMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  cpiMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  cpiMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  cpiMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  consumerSentimentMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  consumerSentimentMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  consumerSentimentMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  consumerSentimentMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  retailSalesMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  retailSalesMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  retailSalesMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  retailSalesMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  durableGoodsMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  durableGoodsMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  durableGoodsMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  durableGoodsMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  unemploymentRateMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  unemploymentRateMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  unemploymentRateMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  unemploymentRateMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  nonfarmPayrollMonthlyIncreaseBuy: [...CONTINUOUS_MOVEMENT],
  nonfarmPayrollMonthlyDecreaseBuy: [...CONTINUOUS_MOVEMENT],
  nonfarmPayrollMonthlyIncreaseSell: [...CONTINUOUS_MOVEMENT],
  nonfarmPayrollMonthlyDecreaseSell: [...CONTINUOUS_MOVEMENT],
  gdpYearlyChangeAboveBuy: [...PERCENT_CHANGE],
  gdpYearlyChangeAboveSell: [...PERCENT_CHANGE],
  gdpYearlyChangeBelowBuy: [...PERCENT_CHANGE],
  gdpYearlyChangeBelowSell: [...PERCENT_CHANGE],
  gdpQuarterlyChangeAboveBuy: [...PERCENT_CHANGE],
  gdpQuarterlyChangeAboveSell: [...PERCENT_CHANGE],
  gdpQuarterlyChangeBelowBuy: [...PERCENT_CHANGE],
  gdpQuarterlyChangeBelowSell: [...PERCENT_CHANGE],
  gdpQuarterlyYoYChangeAboveBuy: [...PERCENT_CHANGE],
  gdpQuarterlyYoYChangeAboveSell: [...PERCENT_CHANGE],
  gdpQuarterlyYoYChangeBelowBuy: [...PERCENT_CHANGE],
  gdpQuarterlyYoYChangeBelowSell: [...PERCENT_CHANGE],
  cashMaxPercent: [0, 10, 20, 30, 50, 80, 100],
  tickerMinPercent: [1, 2, 3, 5, 8, 13, 21, 34, 55],
  tickerMaxPercent: [1, 2, 3, 5, 8, 13, 21, 34, 55],
  holdingBuyPercent: [1, 2, 3, 5, 8, 13, 21, 34, 55],
  holdingSellPercent: [20, 40, 60, 80, 100],
  tradeFrequency: [
    1, 2, 3, day.WEEK,
    day.HALF_MONTH, day.MONTH,
    day.HALF_QUARTER, day.QUARTER,
    day.HALF_YEAR, day.YEAR,
  ],
  rebalanceFrequency: [
    0, day.WEEK,
    day.HALF_MONTH, day.MONTH,
    day.HALF_QUARTER, day.QUARTER,
    day.HALF_YEAR, day.YEAR,
  ],
  buyPreference: Object.values(preference),
  sellPreference: Object.values(preference),
}
